"use strict";
const $=id=>document.getElementById(id),canvas=$("game"),ctx=canvas.getContext("2d",{alpha:false});
const ui={menu:$("menu"),levelUp:$("levelUp"),augment:$("augment"),augmentChoices:$("augmentChoices"),pause:$("pause"),codex:$("codex"),result:$("result"),difficultyGrid:$("difficultyGrid"),weaponGrid:$("weaponGrid"),choices:$("choices"),hiddenBanner:$("hiddenBanner"),pauseContent:$("pauseContent"),codexContent:$("codexContent"),weaponHud:$("weaponHud"),levelText:$("levelText"),timeText:$("timeText"),killText:$("killText"),hpFill:$("hpFill"),xpFill:$("xpFill"),bossWrap:$("bossWrap"),bossFill:$("bossFill"),bossText:$("bossText"),message:$("message"),joystick:$("joystick"),stick:$("stick"),bestKills:$("bestKills"),bestLevel:$("bestLevel"),bestTime:$("bestTime"),pauseWeapon:$("pauseWeapon"),pauseRun:$("pauseRun"),finalStats:$("finalStats"),resultTitle:$("resultTitle"),soundBtn:$("soundBtn"),startBtn:$("startBtn"),goldHud:$("goldHud"),oreHud:$("oreHud"),dodgeHud:$("dodgeHud"),dodgeBtn:$("dodgeBtn"),dodgeCd:$("dodgeCd"),forge:$("forge"),forgeWeapon:$("forgeWeapon"),oreInventory:$("oreInventory"),oreManagement:$("oreManagement"),forgePreview:$("forgePreview"),weaponInventory:$("weaponInventory"),accountGold:$("accountGold"),accountOre:$("accountOre"),accountWeapons:$("accountWeapons"),combatPortrait:$("combatPortrait"),combatPortraitName:$("combatPortraitName")};
let W=0,H=0,DPR=1,state="menu",last=performance.now(),elapsed=0,spawnTimer=0,bossSpawned=false,boss=null,screenShake=0,flash=0,messageTimer=0,selectedWeapon=null,selectedDifficulty="chuchul",runDuration=300,finalBossAt=240,nextMiniBossAt=60,miniBossCount=0,soundOn=true;
let enemies=[],projectiles=[],gems=[],particles=[],visuals=[],fields=[],delayed=[],hazards=[],chests=[];
const GAME_OBJECT_LIMITS=Object.freeze({xpGemsSoft:700,hazardMaxLife:12,fieldMaxLife:12,visualMaxLife:5,delayedMaxLife:8});
const GamePerf=(()=>{
  let sampleTimer=0,mergedXp=0;
  const peaks={enemies:0,projectiles:0,gems:0,particles:0,visuals:0,fields:0,delayed:0,hazards:0,chests:0};
  const culled={hazards:0,fields:0,visuals:0,delayed:0};
  function counts(){return {enemies:enemies.length,projectiles:projectiles.length,gems:gems.length,particles:particles.length,visuals:visuals.length,fields:fields.length,delayed:delayed.length,hazards:hazards.length,chests:chests.length}}
  function sample(){const now=counts();for(const key of Object.keys(peaks))peaks[key]=Math.max(peaks[key],now[key]||0);return now}
  function tick(dt){sampleTimer-=dt;if(sampleTimer<=0){sampleTimer=.5;sample()}}
  function noteCull(kind,count=1){if(kind in culled)culled[kind]+=count}
  function noteXpMerged(count=1){mergedXp+=count}
  function snapshot(){return {current:sample(),peaks:{...peaks},mergedXp,culled:{...culled}}}
  function reset(){sampleTimer=0;mergedXp=0;for(const key of Object.keys(peaks))peaks[key]=0;for(const key of Object.keys(culled))culled[key]=0;sample()}
  return {tick,noteCull,noteXpMerged,snapshot,reset,limits:GAME_OBJECT_LIMITS};
})();
window.GamePerf=GamePerf;
const keys={},pointer={active:false,id:null,ox:0,oy:0,x:0,y:0},move={x:0,y:0};
const C={sword:"#d8e4e8",spear:"#e2bd77",bow:"#8fc596",poison:"#a47bc0",tao:"#74b9d8",saber:"#d7795f",katana:"#d3d3e9",fist:"#d7aa74"};
// 난이도 수치는 js/data/balance-v14.js에서 관리한다.
const difficultyDefs=GameBalance.difficulties;

const weaponDefs={
 sword:{name:"검",icon:"劍",tag:"검기와 검진",basic:{id:"qingfeng",name:"청풍검결",max:8,desc:"성급에 따라 커지고 늘어나는 초승달 검기를 날린다."},arts:[{id:"meteor",name:"유성검우",max:6,desc:"화면 안의 적을 겨냥해 성급만큼 커지는 검우를 쏟아낸다."},{id:"taiji",name:"태극검진",max:6,desc:"성급에 따라 검의 수·크기·회전 반경이 확장되는 검진을 펼친다."},{id:"tenk",name:"만검귀종",max:5,hidden:true,desc:"사방의 경계에서 수십 자루 귀검이 전장 중앙으로 쇄도한다.",condition:"유성검우·태극검진 습득 + 적 180명 격파",progress:p=>({v:Math.min(1,Math.min(p.metrics.kills/180,p.arts.meteor?1:0,p.arts.taiji?1:0)),text:`격파 ${p.metrics.kills}/180 · 검우 ${p.arts.meteor?"완료":"미습득"} · 검진 ${p.arts.taiji?"완료":"미습득"}`}),ready:p=>p.metrics.kills>=180&&p.arts.meteor>0&&p.arts.taiji>0},{id:"swordheart",name:"검심통명",max:3,hidden:true,desc:"검심이 열려 검기 수와 피해가 함께 상승한다.",condition:"청풍검결 6성 + 경지 20",progress:p=>({v:Math.min(1,Math.min((p.arts.qingfeng||0)/6,p.level/20)),text:`청풍검결 ${p.arts.qingfeng||0}/6성 · 경지 ${p.level}/20`}),ready:p=>(p.arts.qingfeng||0)>=6&&p.level>=20,onLearn:p=>{p.projectileBonus++;p.damageMul*=1.05}}]},
 spear:{name:"창",icon:"槍",tag:"관통과 제압",basic:{id:"sunpierce",name:"관일창",max:8,desc:"긴 창기를 직선으로 쏘아 여러 적을 관통한다."},arts:[{id:"dragonspin",name:"회룡창무",max:6,desc:"주기적으로 창을 크게 휘둘러 주변을 쓸어낸다."},{id:"starfall",name:"낙성창진",max:6,desc:"강한 적의 위치에 창진을 떨어뜨린다."},{id:"overlord",name:"무극패왕창",max:5,hidden:true,desc:"기운을 응축한 뒤 전방을 관통 돌파하고 종점에서 패왕창기를 폭발시킨다.",condition:"누적 관통 타격 150회 + 거한 12명 격파",progress:p=>({v:Math.min(1,Math.min(p.metrics.pierceHits/150,p.metrics.brutes/12)),text:`관통 ${p.metrics.pierceHits}/150 · 거한 ${p.metrics.brutes}/12`}),ready:p=>p.metrics.pierceHits>=150&&p.metrics.brutes>=12},{id:"dragonvein",name:"용맥개창",max:3,hidden:true,desc:"창기 관통과 범위가 크게 증가한다.",condition:"관일창 6성 + 관통 260회",progress:p=>({v:Math.min(1,Math.min((p.arts.sunpierce||0)/6,p.metrics.pierceHits/260)),text:`관일창 ${p.arts.sunpierce||0}/6성 · 관통 ${p.metrics.pierceHits}/260`}),ready:p=>(p.arts.sunpierce||0)>=6&&p.metrics.pierceHits>=260,onLearn:p=>{p.pierceBonus++;p.areaMul*=1.06}}]},
 bow:{name:"활",icon:"弓",tag:"원거리 연사",basic:{id:"rapidbow",name:"연주궁",max:8,desc:"빠른 화살을 연속으로 쏘아 먼 적을 사냥한다."},arts:[{id:"piercearrow",name:"관통신전",max:6,desc:"기본 화살의 관통력과 위력이 증가한다."},{id:"arrowrain",name:"천라화살비",max:6,desc:"넓은 범위에 화살비를 퍼붓는다."},{id:"sunmoon",name:"일월신궁",max:5,hidden:true,desc:"태양과 달의 화살이 번갈아 폭발한다.",condition:"원거리 격파 80명 + 천라화살비 3성",progress:p=>({v:Math.min(1,Math.min(p.metrics.rangedKills/80,(p.arts.arrowrain||0)/3)),text:`원거리 격파 ${p.metrics.rangedKills}/80 · 화살비 ${p.arts.arrowrain||0}/3성`}),ready:p=>p.metrics.rangedKills>=80&&(p.arts.arrowrain||0)>=3},{id:"heaveneye",name:"천리신안",max:3,hidden:true,desc:"모든 화살이 약점을 꿰뚫어 치명타 확률이 오른다.",condition:"원거리 격파 160명 + 경지 20",progress:p=>({v:Math.min(1,Math.min(p.metrics.rangedKills/160,p.level/20)),text:`원거리 격파 ${p.metrics.rangedKills}/160 · 경지 ${p.level}/20`}),ready:p=>p.metrics.rangedKills>=160&&p.level>=20,onLearn:p=>{p.critChance+=.07;p.critDamage+=.12}}]},
 poison:{name:"암기(독)",icon:"毒",tag:"추적과 중독",basic:{id:"needle",name:"비연독침",max:8,desc:"적을 추적하는 독침으로 중독을 누적시킨다."},arts:[{id:"thousand",name:"천수관음",max:6,desc:"부채꼴로 수많은 암기를 흩뿌린다."},{id:"miasma",name:"오독연무",max:6,desc:"지속 피해를 주는 독무를 전장에 남긴다."},{id:"lifedeath",name:"생사부",max:5,hidden:true,desc:"주변 적의 생기를 빼앗는 생사부를 폭발시킨다.",condition:"중독으로 90명 격파 + 오독연무 3성",progress:p=>({v:Math.min(1,Math.min(p.metrics.poisonKills/90,(p.arts.miasma||0)/3)),text:`중독 격파 ${p.metrics.poisonKills}/90 · 독무 ${p.arts.miasma||0}/3성`}),ready:p=>p.metrics.poisonKills>=90&&(p.arts.miasma||0)>=3},{id:"poisonbody",name:"만독진신",max:3,hidden:true,desc:"독의 위력이 상승하고 피해를 견디는 육신을 얻는다.",condition:"중독 격파 150명 + 누적 피해 180",progress:p=>({v:Math.min(1,Math.min(p.metrics.poisonKills/150,p.metrics.damageTaken/180)),text:`중독 격파 ${p.metrics.poisonKills}/150 · 누적 피해 ${Math.floor(p.metrics.damageTaken)}/180`}),ready:p=>p.metrics.poisonKills>=150&&p.metrics.damageTaken>=180,onLearn:p=>{p.poisonMul*=1.18;p.damageReduction=Math.min(.5,p.damageReduction+.03)}}]},
 tao:{name:"도술",icon:"符",tag:"오행과 번개",basic:{id:"thunderseal",name:"벽력부",max:8,desc:"부적의 벼락이 적 사이를 연쇄한다."},arts:[{id:"firedragon",name:"화룡주",max:6,desc:"폭발하는 화염 구슬을 발사한다."},{id:"icearray",name:"빙혼진",max:6,desc:"주변에 냉기진을 펼쳐 적을 둔화시킨다."},{id:"fivethunder",name:"오뢰정법",max:5,hidden:true,desc:"하늘에서 다섯 갈래 신뢰가 연속으로 떨어진다.",condition:"오행 속성 격파 100명 + 화룡주·빙혼진 습득",progress:p=>({v:Math.min(1,Math.min(p.metrics.elementalKills/100,p.arts.firedragon?1:0,p.arts.icearray?1:0)),text:`속성 격파 ${p.metrics.elementalKills}/100 · 화룡 ${p.arts.firedragon?"완료":"미습득"} · 빙혼 ${p.arts.icearray?"완료":"미습득"}`}),ready:p=>p.metrics.elementalKills>=100&&p.arts.firedragon>0&&p.arts.icearray>0},{id:"fiveunity",name:"오행귀일",max:3,hidden:true,desc:"부가 도술의 재사용과 범위가 증가한다.",condition:"화룡주·빙혼진 4성 + 경지 20",progress:p=>({v:Math.min(1,Math.min((p.arts.firedragon||0)/4,(p.arts.icearray||0)/4,p.level/20)),text:`화룡 ${p.arts.firedragon||0}/4 · 빙혼 ${p.arts.icearray||0}/4 · 경지 ${p.level}/20`}),ready:p=>(p.arts.firedragon||0)>=4&&(p.arts.icearray||0)>=4&&p.level>=20,onLearn:p=>{p.cooldownRate*=1.1;p.areaMul*=1.05}}]},
 saber:{name:"박도",icon:"刀",tag:"광역과 강타",basic:{id:"thundersaber",name:"벽력도법",max:8,desc:"전방 넓은 범위를 한 번에 베어낸다."},arts:[{id:"whirlwind",name:"선풍참",max:6,desc:"회전하는 도기가 몸 주위를 연속으로 휩쓴다."},{id:"mountain",name:"단악참",max:6,desc:"산을 가르는 묵직한 도격을 내려친다."},{id:"demon",name:"천마군림도",max:5,hidden:true,desc:"피를 대가로 전방위를 찢는 천마도를 펼친다.",condition:"누적 피해 300 + 저체력 상태 8초 유지",progress:p=>({v:Math.min(1,Math.min(p.metrics.damageTaken/300,p.metrics.lowHpTime/8)),text:`받은 피해 ${Math.floor(p.metrics.damageTaken)}/300 · 저체력 ${p.metrics.lowHpTime.toFixed(1)}/8초`}),ready:p=>p.metrics.damageTaken>=300&&p.metrics.lowHpTime>=8},{id:"bloodsaber",name:"천마신공",max:3,hidden:true,desc:"잃은 체력에 비례해 방어가 강해지고, 성급에 따라 박도 무공의 공격 범위가 증가한다. 습득 시 절기 천마합일이 진천마합일로 승격한다.",condition:"저체력 16초 + 거한 24명 격파",progress:p=>({v:Math.min(1,Math.min(p.metrics.lowHpTime/16,p.metrics.brutes/24)),text:`저체력 ${p.metrics.lowHpTime.toFixed(1)}/16초 · 거한 ${p.metrics.brutes}/24`}),ready:p=>p.metrics.lowHpTime>=16&&p.metrics.brutes>=24}]},
 katana:{name:"왜도",icon:"斬",tag:"발도와 연속참",basic:{id:"iai",name:"일섬 발도술",max:8,desc:"성급에 따라 참격 수가 증가하며 적과 그 뒤의 공간을 연속으로 벤다."},arts:[{id:"moonchain",name:"월영연참",max:6,desc:"성급에 따라 연쇄 횟수와 도약 거리가 증가하는 달빛 연속참을 연결한다."},{id:"zanshin",name:"잔심",max:6,desc:"이동 중 남긴 잔상이 뒤늦게 검격을 터뜨린다."},{id:"nameless",name:"무명신풍류",max:5,hidden:true,desc:"시야 전체를 가르는 무수한 무명참을 펼친다.",condition:"무피격 연속 25초 + 정예 25명 격파",progress:p=>({v:Math.min(1,Math.min(p.metrics.maxNoHit/25,p.metrics.elites/25)),text:`최장 무피격 ${p.metrics.maxNoHit.toFixed(1)}/25초 · 정예 ${p.metrics.elites}/25`}),ready:p=>p.metrics.maxNoHit>=25&&p.metrics.elites>=25},{id:"voidslash",name:"공선일체",max:3,hidden:true,desc:"보법 뒤 첫 발도에 치명적인 무아의 칼날이 깃든다.",condition:"회피 18회 + 월영연참 4성",progress:p=>({v:Math.min(1,Math.min(p.metrics.dodges/18,(p.arts.moonchain||0)/4)),text:`회피 ${p.metrics.dodges}/18 · 월영연참 ${p.arts.moonchain||0}/4성`}),ready:p=>p.metrics.dodges>=18&&(p.arts.moonchain||0)>=4,onLearn:p=>{p.dodgeCooldownMul*=.9;p.critChance+=.05}}]},
 fist:{name:"장과 권",icon:"拳",tag:"충격파와 반격",basic:{id:"ironmount",name:"철산고",max:8,desc:"가까운 적에게 강한 충격파를 내질러 밀쳐낸다."},arts:[{id:"hundredstep",name:"백보신권",max:6,desc:"먼 거리까지 뻗는 권풍을 발사한다."},{id:"taijifist",name:"태극권",max:6,desc:"주기적으로 주변 적의 힘을 흘려 밀어낸다."},{id:"dragonreturn",name:"항룡유회",max:5,hidden:true,desc:"금빛 용형의 장력이 전장을 관통한다.",condition:"근거리 격파 70명 + 밀쳐내기 80회",progress:p=>({v:Math.min(1,Math.min(p.metrics.closeKills/70,p.metrics.knockbacks/80)),text:`근거리 격파 ${p.metrics.closeKills}/70 · 밀쳐내기 ${p.metrics.knockbacks}/80`}),ready:p=>p.metrics.closeKills>=70&&p.metrics.knockbacks>=80},{id:"diamondbody",name:"금강나한체",max:3,hidden:true,desc:"근접 전투의 충격을 흡수해 기혈과 방어가 상승한다.",condition:"밀쳐내기 150회 + 경지 20",progress:p=>({v:Math.min(1,Math.min(p.metrics.knockbacks/150,p.level/20)),text:`밀쳐내기 ${p.metrics.knockbacks}/150 · 경지 ${p.level}/20`}),ready:p=>p.metrics.knockbacks>=150&&p.level>=20,onLearn:p=>{p.maxHp+=18;p.hp+=18;p.damageReduction=Math.min(.5,p.damageReduction+.04)}}]}
};
const universal=[
{id:"body",name:"금강공",max:7,tag:"내공",desc:"최대 체력 +22, 체력 22 회복",apply:p=>{p.maxHp+=22;p.hp=Math.min(p.maxHp,p.hp+22)}},
{id:"steps",name:"제운종",max:7,tag:"신법",desc:"이동 속도 +10%",apply:p=>p.speed*=1.1},
{id:"inner",name:"자하심법",max:7,tag:"내공",desc:"모든 무공 피해 +9%",apply:p=>p.damageMul*=1.09},
{id:"sense",name:"청명안",max:6,tag:"감각",desc:"기운 및 전리품 흡수 범위 +34",apply:p=>p.pickup+=34},
{id:"breath",name:"회춘결",max:5,tag:"내공",desc:"8초마다 체력 3 회복",apply:p=>p.regen+=3},
{id:"split",name:"천기분광",max:3,tag:"투사체",desc:"투사체형 기본 무공 발사 수 +1",apply:p=>p.projectileBonus++},
{id:"piercing",name:"파갑진기",max:4,tag:"관통",desc:"모든 투사체 관통 +1",apply:p=>p.pierceBonus++},
{id:"vast",name:"기해확장",max:5,tag:"범위",desc:"범위형 무공 크기 +10%",apply:p=>p.areaMul*=1.1},
{id:"crit",name:"회광심법",max:5,tag:"치명",desc:"치명타 확률 +5%, 치명타 피해 증가",apply:p=>{p.critChance+=.05;p.critDamage+=.1}},
{id:"meteorstep",name:"추풍보",max:5,tag:"보법",desc:"회피 거리 +9%, 재사용 대기시간 -7%",apply:p=>{p.dodgeDistanceMul*=1.09;p.dodgeCooldownMul*=.93}},
{id:"cloudstep",name:"유운보",max:3,tag:"보법",desc:"회피 후 1.4초 동안 이동속도 증가",apply:p=>p.cloudStep++},
{id:"lingbo",name:"능파미보",max:3,tag:"보법",desc:"회피 시작 지점에 공격하는 잔상을 남김",apply:p=>p.lingbo++},
{id:"shrink",name:"축지성촌",max:3,tag:"보법",desc:"회피 무적시간과 경로 피해 증가",apply:p=>{p.shrinkStep++;p.dodgeInvuln+=.035}}
];
const augmentDefs=[
 {id:"killing",name:"살기 응축",max:6,desc:"모든 피해 +13%",apply:p=>p.damageMul*=1.13},
 {id:"chain",name:"연환기",max:5,desc:"기본 무공 공격 속도 +11%",apply:p=>p.attackSpeedMul*=.89},
 {id:"ironwall",name:"철벽강기",max:5,desc:"받는 피해 8% 감소",apply:p=>p.damageReduction=Math.min(.42,p.damageReduction+.08)},
 {id:"marrow",name:"역근세수",max:5,desc:"최대 체력 +28, 체력 28 회복",apply:p=>{p.maxHp+=28;p.hp=Math.min(p.maxHp,p.hp+28)}},
 {id:"gather",name:"축기단",max:5,desc:"획득 경험치 +18%",apply:p=>p.xpMul*=1.18},
 {id:"swallow",name:"제비경",max:5,desc:"이동 속도 +10%",apply:p=>p.speed*=1.1},
 {id:"absorb",name:"흡성잔결",max:5,desc:"흡수 범위 +40, 재생 +2",apply:p=>{p.pickup+=40;p.regen+=2}},
 {id:"break",name:"파진결",max:5,desc:"중간 보스와 혈마에게 주는 피해 +20%",apply:p=>p.eliteDamageMul*=1.2},
 {id:"return",name:"혈환공",max:4,desc:"적 격파 시 체력 0.3 회복",apply:p=>p.killHeal+=.3},
 {id:"circulation",name:"주천운행",max:5,desc:"모든 부가 무공 재사용 속도 +12%",apply:p=>p.cooldownRate*=1.12}
];
const gradeDefs=[
{id:"common",name:"일반",color:"#c7c7c7"},{id:"rare",name:"희귀",color:"#68a7ff"},{id:"epic",name:"서사",color:"#bd79ff"},{id:"unique",name:"고유",color:"#ef9c4c"},{id:"legendary",name:"전설",color:"#ff5d57"},{id:"mythic",name:"신화",color:"#ff80d8"},{id:"eternal",name:"영원",color:"#e8f8ff"}
];
const oreTypes={han:{name:"한철",ability:"강철심",desc:"기본 피해 증가"},moon:{name:"월은",ability:"월광날",desc:"치명타 확률 증가"},black:{name:"현철",ability:"중악",desc:"무공 범위 증가"},poison:{name:"독옥",ability:"독맥",desc:"지속 피해 강화"},fire:{name:"화정석",ability:"화맥",desc:"타격 시 화염 폭발 가능"},ice:{name:"빙정석",ability:"빙심",desc:"피해 감소와 적 둔화"},thunder:{name:"뇌정석",ability:"뇌맥",desc:"부가 무공 가속과 연쇄 번개"}};
let account={gold:0,ores:{},weapons:[],equipped:{},forgeCount:0};
