"use strict";
function resetGame(){enemies=[];projectiles=[];gems=[];particles=[];visuals=[];fields=[];delayed=[];hazards=[];chests=[];elapsed=0;spawnTimer=0;bossSpawned=false;boss=null;screenShake=0;flash=0;miniBossCount=0;nextMiniBossAt=60;const diff=difficultyDefs[selectedDifficulty];runDuration=diff.duration;finalBossAt=diff.bossAt;Object.assign(player,{x:0,y:0,facing:-Math.PI/2,moving:false,hp:100,maxHp:100,speed:170,level:1,xp:0,xpNeed:xpRequirement(1),kills:0,pickup:78,damageMul:1,eliteDamageMul:1,damageReduction:0,attackSpeedMul:1,xpMul:1,cooldownRate:1,killHeal:0,regen:0,regenTimer:8,invuln:0,fireTimer:.2,projectileBonus:0,pierceBonus:0,areaMul:1,critChance:.03,critDamage:1.5,projectileSpeedMul:1,poisonMul:1,dodgeCooldown:0,dodgeCooldownMul:1,dodgeDistanceMul:1,dodgeTimer:0,dodgeDuration:.18,dodgeInvuln:.2,dodgeVx:0,dodgeVy:0,cloudStep:0,lingbo:0,shrinkStep:0,speedBuff:0,arts:{},universal:Object.fromEntries(universal.map(u=>[u.id,0])),augments:{},chestsOpened:0,midBossKills:0,cooldowns:{meteor:0,tenk:0,dragonspin:0,starfall:0,overlord:0,arrowrain:0,sunmoon:0,thousand:0,miasma:0,lifedeath:0,firedragon:0,icepulse:0,fivethunder:0,whirlwind:0,mountain:0,demon:0,moonchain:0,zanshinDrop:0,nameless:0,hundredstep:0,taijifist:0,dragonreturn:0},hiddenReady:{},hiddenNotified:{},runGold:0,runOres:{},forgedWeapon:null,metrics:{kills:0,rangedKills:0,closeKills:0,poisonKills:0,elementalKills:0,pierceHits:0,brutes:0,elites:0,damageTaken:0,lowHpTime:0,noHit:0,maxNoHit:0,knockbacks:0,dodges:0}});const w=weaponDefs[selectedWeapon];player.arts[w.basic.id]=1;for(const a of w.arts)player.arts[a.id]=0;applyForgedWeapon();ui.weaponHud.textContent=`${w.name} · ${diff.name}${player.forgedWeapon?" · "+player.forgedWeapon.name:""}`;ui.bossWrap.style.display="none";updateHud()}

function startGame(){if(!selectedWeapon||difficultyDefs[selectedDifficulty].locked)return;initAudio();resetGame();state="playing";[ui.menu,ui.result,ui.pause,ui.levelUp,ui.augment,ui.forge].forEach(x=>x.classList.remove("show"));ui.dodgeBtn.style.display="flex";showMessage(`${difficultyDefs[selectedDifficulty].name} · ${weaponDefs[selectedWeapon].name}의 길이 시작되었다`,2);last=performance.now()}
function endGame(win,reason=""){state=win?"victory":"gameover";pointer.active=false;ui.joystick.style.display="none";ui.dodgeBtn.style.display="none";if(win){const clear=Math.floor(80*difficultyDefs[selectedDifficulty].rank);account.gold+=clear;player.runGold+=clear}saveRecords();ui.resultTitle.textContent=win?"천하에 이름을 떨쳤다":reason==="time"?"혈겁에 삼켜졌다":"주화입마";const w=weaponDefs[selectedWeapon],d=difficultyDefs[selectedDifficulty],hiddenCount=w.arts.filter(a=>a.hidden&&(player.arts[a.id]||0)>0).length,oreCount=Object.values(player.runOres).reduce((a,b)=>a+b,0);ui.finalStats.innerHTML=`난이도 <b>${d.name}</b> · 무기군 <b>${w.name}</b><br>생존 <b>${fmtTime(elapsed)}</b> · 격파 <b>${player.kills}명</b><br>중간 보스 <b>${player.midBossKills}명</b> · 도달 경지 <b>${player.level}</b><br>획득 <b>금자 ${Math.floor(player.runGold)}</b> · 광석 <b>${oreCount}개</b><br>히든 무공 <b>${hiddenCount}개 습득</b>${player.forgedWeapon?`<br>장착 무기 <b>${player.forgedWeapon.name}</b>`:""}${reason==="time"?'<br><span class="danger-note">제한시간 안에 혈마를 처치하지 못했다.</span>':""}`;ui.result.classList.add("show");GameAudio.playUI(win?"victory":"defeat")}

function pauseGame(){if(state!=="playing")return;state="paused";ui.dodgeBtn.style.display="none";renderPause();ui.pause.classList.add("show")}
function resumeGame(){if(state!=="paused")return;state="playing";ui.pause.classList.remove("show");ui.dodgeBtn.style.display="flex";last=performance.now()}
function renderPause(){const w=weaponDefs[selectedWeapon],d=difficultyDefs[selectedDifficulty];ui.pauseWeapon.textContent=`${w.icon} ${w.name} · ${d.name}`;ui.pauseRun.textContent=`남은 ${fmtTime(runDuration-elapsed)} · 격파 ${player.kills}`;const stat=[["체력",`${Math.ceil(player.hp)}/${player.maxHp}`],["피해 배율",`${player.damageMul.toFixed(2)}x`],["피해 감소",`${Math.round(player.damageReduction*100)}%`],["투사체",`+${player.projectileBonus}`],["관통",`+${player.pierceBonus}`],["치명타",`${Math.round(player.critChance*100)}%`],["범위",`${player.areaMul.toFixed(2)}x`],["회피 쿨",`${Math.max(1.05,4.2*player.dodgeCooldownMul).toFixed(1)}초`],["경지",player.level]];const arts=[w.basic,...w.arts];const augmentRows=augmentDefs.filter(a=>(player.augments[a.id]||0)>0).map(a=>`<div class="augment-row"><strong><span>${a.name}</span><span>${player.augments[a.id]}중</span></strong><p>${a.desc}</p></div>`).join("")||'<p class="desc">아직 획득한 증강이 없다.</p>';const passiveRows=universal.filter(a=>(player.universal[a.id]||0)>0).map(a=>`<div class="augment-row"><strong><span>${a.name}</span><span>${player.universal[a.id]}성</span></strong><p>${a.desc}</p></div>`).join("")||'<p class="desc">아직 공통 심법을 익히지 않았다.</p>';ui.pauseContent.innerHTML=`<h3>전투 상황</h3><div class="stat-grid"><div class="stat"><b>${d.name}</b><span>난이도</span></div><div class="stat"><b>${fmtTime(runDuration-elapsed)}</b><span>남은 시간</span></div><div class="stat"><b>${player.midBossKills}</b><span>중간 보스</span></div></div><h3>현재 능력</h3><div class="stat-grid">${stat.map(s=>`<div class="stat"><b>${s[1]}</b><span>${s[0]}</span></div>`).join("")}</div>${player.forgedWeapon?`<h3>장착 무기</h3><div class="art-row"><strong><span>${player.forgedWeapon.name}</span><span>${player.forgedWeapon.damageMul.toFixed(2)}x</span></strong><p>${player.forgedWeapon.abilityName} · ${player.forgedWeapon.abilityDesc}</p></div>`:""}<h3>습득 무공</h3><div class="art-list">${arts.map(a=>{const lv=player.arts[a.id]||0,prog=a.hidden?a.progress(player):null;return`<div class="art-row ${lv?"":"locked"}"><strong><span>${a.hidden?"✦ ":""}${a.name}</span><span>${lv?lv+"성":"미습득"}</span></strong><p>${a.desc}</p>${a.hidden&&!lv?`<p>조건: ${a.condition}<br>${prog.text}</p><div class="progress"><span style="width:${prog.v*100}%"></span></div>`:""}</div>`}).join("")}</div><h3>공통 심법·보법</h3><div class="art-list">${passiveRows}</div><h3>증강</h3><div class="art-list">${augmentRows}</div><h3>이번 원정 전리품</h3><div class="stat-grid"><div class="stat"><b>${Math.floor(player.runGold)}</b><span>금자</span></div><div class="stat"><b>${Object.values(player.runOres).reduce((a,b)=>a+b,0)}</b><span>광석</span></div><div class="stat"><b>${player.metrics.dodges}</b><span>회피</span></div></div>`}


function checkHidden(){for(const h of weaponDefs[selectedWeapon].arts.filter(a=>a.hidden)){if(!player.hiddenReady[h.id]&&h.ready(player)){player.hiddenReady[h.id]=true;if(!player.hiddenNotified[h.id]){player.hiddenNotified[h.id]=true;showMessage(`히든 무공의 단서 완성: ${h.name}`,3);GameAudio.playUI("hidden-ready")}}}}
function choicePool(){const w=weaponDefs[selectedWeapon],pool=[];const arts=[w.basic,...w.arts];for(const a of arts){const lv=player.arts[a.id]||0;if(a.hidden&&!player.hiddenReady[a.id]&&lv===0)continue;if(lv<a.max){pool.push({kind:"art",id:a.id,name:a.name,tag:a.hidden?"히든 무공":lv?"무공 강화":"무공 습득",desc:lv?`${lv+1}성: ${a.desc}`:`새 무공 해금: ${a.desc}`,apply:()=>{player.arts[a.id]=lv+1;if(a.onLearn)a.onLearn(player,lv+1)}})}}for(const u of universal){const lv=player.universal[u.id]||0;if(lv<u.max)pool.push({kind:"universal",id:u.id,name:u.name,tag:u.tag||"내공·신법",desc:`${lv+1}성: ${u.desc}`,apply:()=>{player.universal[u.id]=lv+1;u.apply(player)}})}return pool}
function levelChoice(){
  state="levelup";
  ui.dodgeBtn.style.display="none";

  const pool=choicePool();
  const artPool=pool.filter(x=>x.kind==="art");
  const pick=[];

  /** 중복 없이 무작위 선택지를 하나 뽑는다. */
  function take(src){
    if(!src.length)return;
    const i=Math.floor(Math.random()*src.length);
    const choice=src.splice(i,1)[0];
    const j=pool.indexOf(choice);
    if(j>=0)pool.splice(j,1);
    pick.push(choice);
  }

  take(artPool);
  take(artPool);
  while(pick.length<3&&pool.length)take(pool);

  // 모든 유한 성장 요소를 완성한 뒤에도 게임이 멈추지 않도록 반복 보상을 제공한다.
  const repeatChoices=[
    {kind:"repeat",name:"내공 정련",tag:"반복 성장",desc:"모든 피해가 영구적으로 2% 증가한다.",apply:()=>{player.damageMul*=1.02}},
    {kind:"repeat",name:"기혈 순환",tag:"반복 성장",desc:"최대 체력이 5 증가하고 최대 체력의 20%를 회복한다.",apply:()=>{player.maxHp+=5;player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.2)}},
    {kind:"repeat",name:"신법 연마",tag:"반복 성장",desc:"이동속도가 1.5% 증가하고 보법 재사용 대기시간이 1% 감소한다.",apply:()=>{player.speed*=1.015;player.dodgeCooldownMul=Math.max(.55,player.dodgeCooldownMul*.99)}}
  ];
  for(const reward of repeatChoices){
    if(pick.length>=3)break;
    pick.push(reward);
  }

  const ready=weaponDefs[selectedWeapon].arts.filter(a=>a.hidden&&player.hiddenReady[a.id]&&!player.arts[a.id]);
  ui.hiddenBanner.innerHTML=ready.length?`<div class="unlock-banner">히든 단서 완성: ${ready.map(a=>a.name).join(" · ")}</div><div style="height:9px"></div>`:"";
  ui.choices.innerHTML="";

  pick.forEach(choice=>{
    const button=document.createElement("button");
    button.type="button";
    button.className="choice";
    button.innerHTML=`<strong>${choice.name}<span class="tag">${choice.tag}</span></strong><small>${choice.desc}</small>`;
    button.addEventListener("click",()=>{
      choice.apply();
      ui.levelUp.classList.remove("show");
      state="playing";
      ui.dodgeBtn.style.display="flex";
      GameAudio.playUI("level-choice");
      showMessage(`${choice.name}의 깨달음을 얻었다`,1.5);
      last=performance.now();
    },{once:true});
    ui.choices.appendChild(button);
  });
  ui.levelUp.classList.add("show");
}
function openAugmentChoice(){state="augment";ui.dodgeBtn.style.display="none";const pool=augmentDefs.filter(a=>(player.augments[a.id]||0)<a.max),pick=[];while(pool.length&&pick.length<3)pick.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);if(!pick.length){player.hp=player.maxHp;state="playing";ui.dodgeBtn.style.display="flex";showMessage("모든 증강을 완성해 기혈이 회복되었다",1.5);return}ui.augmentChoices.innerHTML="";pick.forEach(a=>{const lv=player.augments[a.id]||0,b=document.createElement("button");b.type="button";b.className="choice";b.innerHTML=`<strong>${a.name}<span class="tag">증강 ${lv+1}/${a.max}</span></strong><small>${a.desc}</small>`;b.addEventListener("click",()=>{player.augments[a.id]=lv+1;a.apply(player);ui.augment.classList.remove("show");state="playing";ui.dodgeBtn.style.display="flex";showMessage(`${a.name} 증강을 획득했다`,1.5);GameAudio.playUI("augment-take");last=performance.now()},{once:true});ui.augmentChoices.appendChild(b)});ui.augment.classList.add("show");GameAudio.playUI("augment-open")}
function gainXp(n){player.xp+=n*player.xpMul;let up=false;while(player.xp>=player.xpNeed){player.xp-=player.xpNeed;player.level++;player.xpNeed=xpRequirement(player.level);up=true}if(up)levelChoice()}

function enemyDef(type){
  const difficulty=difficultyDefs[selectedDifficulty],base=GameBalance.enemyArchetypes[type]||GameBalance.enemyArchetypes.bandit;
  const scale=(1+elapsed/difficulty.scaleTime)*difficulty.enemyHp;
  return {r:base.r,hp:base.hp*scale,speed:(base.speed+elapsed*base.speedGrowth)*difficulty.enemySpeed,damage:base.damage*difficulty.enemyDamage,xp:base.xp,color:base.color};
}

function spawnEnemy(type,x,y){const d=enemyDef(type);enemies.push({type,x,y,r:d.r,hp:d.hp,maxHp:d.hp,speed:d.speed,damage:d.damage,xp:d.xp,color:d.color,hit:0,orbitHit:0,pushX:0,pushY:0,slow:1,slowTime:0,poison:0,poisonTime:0,poisonTick:0,dead:false})}
function spawnAround(type,dist=0){const a=Math.random()*Math.PI*2,r=dist||Math.max(W,H)*.63+90+Math.random()*140;spawnEnemy(type,player.x+Math.cos(a)*r,player.y+Math.sin(a)*r)}
function spawnMiniBoss(){miniBossCount++;const d=difficultyDefs[selectedDifficulty],a=Math.random()*Math.PI*2,r=Math.max(W,H)*.63+150,types=[{subtype:"blackblade",name:"흑도객",color:"#653d37",speed:60,r:26},{subtype:"poisonhand",name:"독수귀",color:"#665078",speed:52,r:25},{subtype:"ironmonk",name:"철탑승",color:"#71624d",speed:43,r:30}],t=types[(miniBossCount-1)%types.length],hp=d.miniHp+d.miniGrowth*miniBossCount+player.level*32,e={type:"midboss",subtype:t.subtype,bossName:t.name,x:player.x+Math.cos(a)*r,y:player.y+Math.sin(a)*r,r:t.r,hp,maxHp:hp,speed:t.speed*d.enemySpeed,damage:d.miniDamage+miniBossCount*1.5,xp:0,color:t.color,hit:0,orbitHit:0,pushX:0,pushY:0,slow:1,slowTime:0,poison:0,poisonTime:0,poisonTick:0,dead:false,special:2.3,chargeDelay:0,chargeTime:0,chargeVx:0,chargeVy:0};enemies.push(e);showMessage(`${miniBossCount}분 중간 보스 · ${t.name} 출현`,2.2);GameAudio.playSFX("midboss-spawn")}
function spawnBoss(){bossSpawned=true;const d=difficultyDefs[selectedDifficulty],a=Math.random()*Math.PI*2,r=Math.max(W,H)*.65+160,hp=d.bossHp+player.level*d.bossLevelHp;boss={type:"boss",bossName:"혈마",x:player.x+Math.cos(a)*r,y:player.y+Math.sin(a)*r,r:43,hp,maxHp:hp,speed:d.bossSpeed,damage:d.bossDamage,xp:0,color:"#8b2929",hit:0,orbitHit:0,pushX:0,pushY:0,slow:1,slowTime:0,poison:0,poisonTime:0,poisonTick:0,dead:false,summon:d.summon,blast:d.blast,dash:d.dash,orbs:d.orbs,phase2:false,chargeDelay:0,chargeTime:0,chargeVx:0,chargeVy:0};enemies.push(boss);ui.bossWrap.style.display="block";showMessage(`${d.name}의 혈마가 강림했다 · 1분 안에 처치하라`,3);GameAudio.playSFX("boss-spawn")}
function nearest(max=820,fromX=player.x,fromY=player.y,exclude=[]){let b=null,bd=max*max;for(const e of GameSpatial.queryCircle(fromX,fromY,max)){if(e.dead||exclude.includes(e))continue;const dx=e.x-fromX,dy=e.y-fromY,d=dx*dx+dy*dy;if(d<bd){bd=d;b=e}}return b}
function addVisual(v){visuals.push(Object.assign({life:.3,max:.3,color:C[selectedWeapon]},v))}
function particle(x,y,color=C[selectedWeapon],speed=80,n=1){const q=account.settings?.quality||"normal",limit=q==="low"?GameBalance.limits.maxParticlesLow:q==="high"?GameBalance.limits.maxParticlesHigh:GameBalance.limits.maxParticlesNormal;for(let i=0;i<n&&particles.length<limit;i++){const a=Math.random()*Math.PI*2,s=Math.random()*speed;particles.push(GamePools.particle.acquire({x:0,y:0,vx:0,vy:0,life:0,max:.6,color:"#fff"},{x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,max:.6,color}))}}
function projectile(o){const p=GamePools.projectile.acquire({x:player.x,y:player.y,vx:0,vy:0,r:4,life:1.5,damage:15,pierce:0,hits:0,shape:"blade",color:C[selectedWeapon],source:"basic",homing:0,poison:0,explode:0,knock:0,elemental:false,trail:0,ignorePassive:false},o);if(!p.ignorePassive){p.pierce+=player.pierceBonus;p.vx*=player.projectileSpeedMul;p.vy*=player.projectileSpeedMul;p.poison*=player.poisonMul}projectiles.push(p)}
function facingAngle(){return Number.isFinite(player.facing)?player.facing:-Math.PI/2}
function visibleEnemies(margin=42){const l=player.x-W/2+margin,r=player.x+W/2-margin,t=player.y-H/2+margin,b=player.y+H/2-margin;return enemies.filter(e=>!e.dead&&e.x>l&&e.x<r&&e.y>t&&e.y<b)}
function taijiCount(lv){return Math.min(8,1+lv+Math.floor(lv/3))}
function taijiRadius(lv){return 50+lv*11}
function taijiBladeSize(lv){return 9+lv*1.8}
function katanaSlashCount(lv){return Math.min(5,1+Math.floor(lv/2))}
function aoe(x,y,r,damage,source,opt={}){r*=player.areaMul;addVisual({type:"ring",x,y,r,life:.32,max:.32,color:opt.color||C[selectedWeapon],width:opt.width||5,source:opt.vfxSource||source});for(const e of GameSpatial.queryCircle(x,y,r+64)){if(e.dead)continue;const d=Math.hypot(e.x-x,e.y-y);if(d<r+e.r){damageEnemy(e,damage,source,Object.assign({},opt,{distance:d}));if(opt.knock){const n=d||1;e.pushX+=(e.x-x)/n*opt.knock;e.pushY+=(e.y-y)/n*opt.knock;player.metrics.knockbacks++}}}}
function lineHit(x1,y1,x2,y2,width,damage,source,opt={}){width*=Math.sqrt(player.areaMul);addVisual({type:"line",x1,y1,x2,y2,width,life:opt.life||.2,max:opt.life||.2,color:opt.color||C[selectedWeapon],source});const pad=width+64;for(const e of GameSpatial.queryAABB(Math.min(x1,x2)-pad,Math.min(y1,y2)-pad,Math.max(x1,x2)+pad,Math.max(y1,y2)+pad)){if(e.dead)continue;const vx=x2-x1,vy=y2-y1,l2=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((e.x-x1)*vx+(e.y-y1)*vy)/l2)),px=x1+t*vx,py=y1+t*vy,d=Math.hypot(e.x-px,e.y-py);if(d<width+e.r)damageEnemy(e,damage,source,Object.assign({},opt,{distance:Math.hypot(e.x-player.x,e.y-player.y)}))}}
function coneHit(angle,range,half,damage,source,opt={}){range*=player.areaMul;half=Math.min(Math.PI,half*Math.sqrt(player.areaMul));addVisual({type:"cone",x:player.x,y:player.y,a:angle,r:range,half,life:.24,max:.24,color:opt.color||C[selectedWeapon],source});for(const e of GameSpatial.queryCircle(player.x,player.y,range+64)){if(e.dead)continue;const dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy);let da=Math.atan2(dy,dx)-angle;da=Math.atan2(Math.sin(da),Math.cos(da));if(d<range+e.r&&Math.abs(da)<half)damageEnemy(e,damage,source,Object.assign({},opt,{distance:d}));}}
function damageEnemy(e,dmg,source,opt={}){if(e.dead)return;const elite=(e.type==="midboss"||e.type==="boss")?player.eliteDamageMul:1,crit=Math.random()<player.critChance,amount=dmg*player.damageMul*elite*(crit?player.critDamage:1);e.hp-=amount;e.hit=.09;if(crit)addVisual({type:"text",x:e.x,y:e.y-18,text:"치명",life:.32,max:.32,color:"#fff0a8"});screenShake=Math.max(screenShake,opt.shake||1.2);if(opt.poison){e.poison=Math.max(e.poison,opt.poison*player.damageMul*player.poisonMul);e.poisonTime=Math.max(e.poisonTime,opt.poisonTime||5)}if(opt.slow){e.slow=Math.min(e.slow,opt.slow);e.slowTime=Math.max(e.slowTime,opt.slowTime||2)}if(opt.elemental)opt.elemental=true;if(e.hp<=0)killEnemy(e,source,opt);particle(e.x,e.y,opt.color||e.color,55,2)}
function hurtPlayer(amount){if(player.invuln>0||state!=="playing")return;const taken=Math.max(1,amount*(1-player.damageReduction));player.hp-=taken;player.metrics.damageTaken+=taken;player.metrics.noHit=0;player.invuln=.68;flash=.85;screenShake=11;GameAudio.playSFX("player-hurt");if(player.hp<=0){player.hp=0;endGame(false)}}
function rollGrade(rank,boost=0){const r=Math.random(),bonus=Math.min(2,boost+difficultyDefs[selectedDifficulty].oreBonus),tables=[[["common",.82],["rare",.16],["epic",.02]],[["common",.48],["rare",.38],["epic",.12],["unique",.02]],[["rare",.48],["epic",.34],["unique",.15],["legendary",.03]],[["epic",.47],["unique",.32],["legendary",.17],["mythic",.035],["eternal",.005]]],table=tables[Math.min(3,Math.max(0,rank-1+Math.floor(bonus/2)))];let c=0;for(const [g,p] of table){c+=p;if(r<=c)return g}return table[table.length-1][0]}
function dropGold(x,y,amount){gems.push({kind:"gold",x,y,r:6,value:amount,vx:0,vy:0,dead:false})}
function dropOre(x,y,boost=0){const types=Object.keys(oreTypes),type=types[Math.floor(Math.random()*types.length)],grade=rollGrade(difficultyDefs[selectedDifficulty].rank,boost);gems.push({kind:"ore",x,y,r:8,type,grade,vx:0,vy:0,dead:false})}
function grantOre(boost=0){const types=Object.keys(oreTypes),type=types[Math.floor(Math.random()*types.length)],grade=rollGrade(difficultyDefs[selectedDifficulty].rank,boost),k=oreKey(type,grade);account.ores[k]=(account.ores[k]||0)+1;player.runOres[k]=(player.runOres[k]||0)+1;return `${gradeName(grade)} ${oreTypes[type].name}`}
function killEnemy(e,source="basic",opt={}){if(e.dead)return;e.dead=true;player.kills++;player.metrics.kills++;if(player.killHeal)player.hp=Math.min(player.maxHp,player.hp+player.killHeal);const dist=Math.hypot(e.x-player.x,e.y-player.y);if(dist>220)player.metrics.rangedKills++;if(dist<105)player.metrics.closeKills++;if(source==="poison")player.metrics.poisonKills++;if(opt.elemental||source==="elemental")player.metrics.elementalKills++;if(e.type==="brute")player.metrics.brutes++;if(["master","assassin","midboss","boss"].includes(e.type))player.metrics.elites++;
 if(e.type==="boss"){boss=null;ui.bossWrap.style.display="none";const reward=90*difficultyDefs[selectedDifficulty].rank;account.gold+=reward;player.runGold+=reward;for(let i=0;i<1+difficultyDefs[selectedDifficulty].rank;i++)grantOre(2);refreshAccountUI();particle(e.x,e.y,"#d9b95f",210,38);setTimeout(()=>{if(state==="playing")endGame(true)},650);return}
 if(e.type==="midboss"){player.midBossKills++;dropGold(e.x,e.y,20+8*difficultyDefs[selectedDifficulty].rank);dropOre(e.x+18,e.y,1);chests.push({x:e.x,y:e.y,r:13,dead:false,bob:Math.random()*6});particle(e.x,e.y,"#d9b95f",160,24);showMessage(`${e.bossName} 격파 · 광석과 증강 상자`,2);return}
 if(["master","assassin"].includes(e.type)){dropGold(e.x,e.y,3+difficultyDefs[selectedDifficulty].rank);if(Math.random()<.16+.06*difficultyDefs[selectedDifficulty].rank)dropOre(e.x+8,e.y-5,0)}else if(Math.random()<.09)dropGold(e.x,e.y,1);
 gems.push({kind:"xp",x:e.x,y:e.y,r:e.xp>=8?7:5,value:e.xp,vx:0,vy:0,dead:false});if(Math.random()<.03&&player.hp<player.maxHp*.72)gems.push({kind:"heal",x:e.x+6,y:e.y-4,r:7,heal:15,vx:0,vy:0,dead:false})}

function spreadAngles(base,count,spread=.1){const a=[];for(let i=0;i<count;i++)a.push(base+(i-(count-1)/2)*spread);return a}
function fireBasic(){const w=selectedWeapon,t=nearest();if(!t)return;const a=Math.atan2(t.y-player.y,t.x-player.x),lv=player.arts[weaponDefs[w].basic.id];
 if(w==="sword"){const n=Math.min(7,1+Math.floor((lv-1)/2)+player.projectileBonus),spread=.10+.015*lv,size=6+lv*1.25,speed=540+lv*22;spreadAngles(a,n,spread).forEach(aa=>projectile({vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,damage:(16+lv*6)*(n>1?.82:1),r:size,pierce:Math.floor((lv-1)/3),shape:"crescent",trail:1,color:lv>=6?"#eaf7ff":C.sword}));addVisual({type:"slashArc",x:player.x,y:player.y,a,r:22+lv*3,life:.16,max:.16,color:C.sword,width:3+lv*.35});player.fireTimer=.72*Math.pow(.95,lv-1)}
 else if(w==="spear"){const n=1+player.projectileBonus;spreadAngles(a,n,.075).forEach(aa=>projectile({vx:Math.cos(aa)*660,vy:Math.sin(aa)*660,damage:(20+lv*7)*(n>1?.86:1),r:6,pierce:2+Math.floor(lv/2),shape:"spear",trail:1}));player.fireTimer=.9*Math.pow(.95,lv-1)}
 else if(w==="bow"){const n=(lv>=6?3:lv>=3?2:1)+player.projectileBonus;spreadAngles(a,n,.075).forEach(aa=>projectile({vx:Math.cos(aa)*720,vy:Math.sin(aa)*720,damage:(11+lv*4)*(n>3?.9:1),r:3,pierce:player.arts.piercearrow?Math.floor((player.arts.piercearrow+1)/2):0,shape:"arrow",trail:1}));player.fireTimer=.46*Math.pow(.965,lv-1)}
 else if(w==="poison"){const n=1+player.projectileBonus;spreadAngles(a,n,.09).forEach(aa=>projectile({vx:Math.cos(aa)*430,vy:Math.sin(aa)*430,damage:8+lv*3,r:3,pierce:Math.floor(lv/4),shape:"needle",homing:4.5,poison:(4+lv*2),poisonTime:5,trail:1}));player.fireTimer=.55*Math.pow(.96,lv-1)}
 else if(w==="tao"){chainLightning(t,1+Math.floor(lv/3)+player.projectileBonus,11+lv*5,"elemental");player.fireTimer=.82*Math.pow(.95,lv-1)}
 else if(w==="saber"){coneHit(a,82+lv*5,.72,20+lv*7,"basic",{knock:80,shake:3,color:C.saber});player.fireTimer=.92*Math.pow(.95,lv-1)}
 else if(w==="katana"){const n=katanaSlashCount(lv),len=235+lv*17,width=9+lv*1.25,base=22+lv*7,interval=Math.max(.052,.09-lv*.004);for(let i=0;i<n;i++){const off=(i-(n-1)/2)*.09,aa=a+off,side=(i%2?1:-1)*(5+i*2);delayed.push({time:i*interval+.012,type:"katanaSlash",a:aa,side,len:len+i*10,width:width+i*.45,damage:base*(i===0?1:.72),color:i===n-1&&lv>=7?"#ffffff":C.katana,arc:36+lv*3+i*4,arcWidth:2.5+lv*.25,index:i,total:n})}player.fireTimer=Math.max(.62,.82*Math.pow(.95,lv-1)+interval*(n-1)*.35)}
 else if(w==="fist"){const n=1+player.projectileBonus;spreadAngles(a,n,.1).forEach(aa=>projectile({vx:Math.cos(aa)*480,vy:Math.sin(aa)*480,damage:17+lv*6,r:11,pierce:0,shape:"fist",knock:170+lv*12,trail:1}));player.fireTimer=.76*Math.pow(.95,lv-1)}
}
function chainLightning(first,count,damage,source){let current=first,from={x:player.x,y:player.y},used=[];for(let i=0;i<count&&current;i++){addVisual({type:"lightning",x1:from.x,y1:from.y,x2:current.x,y2:current.y,width:3,life:.16,max:.16,color:"#80c8e8"});damageEnemy(current,damage,source,{elemental:true,color:"#80c8e8",shake:2});used.push(current);from=current;current=nearest(175,from.x,from.y,used)}GameAudio.playSFX("lightning-chain")}
function tickArts(dt){const a=player.arts,cd=player.cooldowns;for(const k in cd)cd[k]-=dt*player.cooldownRate;
 if(a.meteor&&cd.meteor<=0){cd.meteor=Math.max(2.25,5.4-a.meteor*.48);let targets=visibleEnemies(58).sort((x,y)=>y.maxHp-x.maxHp).slice(0,2+a.meteor);if(!targets.length){targets=Array.from({length:2+a.meteor},()=>({x:player.x+(Math.random()-.5)*Math.max(120,W-150),y:player.y+(Math.random()-.5)*Math.max(140,H-190)}))}const radius=22+a.meteor*4;for(const e of targets){const delay=.34+Math.random()*.22;addVisual({type:"fallingSword",x:e.x,y:e.y,r:radius,life:delay,max:delay,color:a.meteor>=5?"#eefaff":C.sword,width:4+a.meteor*.4,source:"meteor"});delayed.push({time:delay,type:"strike",x:e.x,y:e.y,r:radius,damage:18+a.meteor*9,color:C.sword,source:"meteor"})}showMessage("유성검우",.7)}
 if(a.taiji){const n=taijiCount(a.taiji),rad=taijiRadius(a.taiji),blade=taijiBladeSize(a.taiji);for(const e of enemies){if(e.dead||e.orbitHit>0)continue;for(let i=0;i<n;i++){const ang=elapsed*(2.15+a.taiji*.11)+i*Math.PI*2/n,bx=player.x+Math.cos(ang)*rad,by=player.y+Math.sin(ang)*rad;if(Math.hypot(e.x-bx,e.y-by)<e.r+blade){damageEnemy(e,8+a.taiji*7,"taiji",{color:C.sword});e.orbitHit=Math.max(.18,.34-a.taiji*.018);break}}}}
 if(a.tenk&&cd.tenk<=0){cd.tenk=Math.max(4.4,8.5-a.tenk*.7);const count=20+a.tenk*8,targets=visibleEnemies(20),hw=W/2+90,hh=H/2+90;addVisual({type:"ring",x:player.x,y:player.y,r:92+a.tenk*15,life:.55,max:.55,color:"#edf8ff",width:4+a.tenk});addVisual({type:"cross",x:player.x,y:player.y,r:130+a.tenk*18,life:.5,max:.5,color:C.sword});for(let i=0;i<count;i++){const side=i%4;let x,y;if(side===0){x=player.x-hw;y=player.y+(Math.random()*2-1)*hh}else if(side===1){x=player.x+hw;y=player.y+(Math.random()*2-1)*hh}else if(side===2){x=player.x+(Math.random()*2-1)*hw;y=player.y-hh}else{x=player.x+(Math.random()*2-1)*hw;y=player.y+hh}const t=targets.length?targets[Math.floor(Math.random()*targets.length)]:null,tx=t?t.x:player.x+(Math.random()-.5)*W*.55,ty=t?t.y:player.y+(Math.random()-.5)*H*.55,ang=Math.atan2(ty-y,tx-x),speed=650+a.tenk*32;projectile({x,y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,damage:24+a.tenk*10,r:6+a.tenk*.35,pierce:2+Math.floor(a.tenk/2),shape:"sword",color:i%5===0?"#ffffff":"#dceff7",life:2.4,source:"tenk",trail:1})}showMessage("만검귀종 · 사방귀검",1)}
 if(a.dragonspin&&cd.dragonspin<=0){cd.dragonspin=Math.max(1.7,4.2-a.dragonspin*.38);aoe(player.x,player.y,105+a.dragonspin*12,17+a.dragonspin*10,"dragonspin",{knock:210,color:C.spear,shake:5});addVisual({type:"spiral",x:player.x,y:player.y,r:115+a.dragonspin*12,life:.45,max:.45,color:C.spear})}
 if(a.starfall&&cd.starfall<=0){cd.starfall=Math.max(2.8,6.4-a.starfall*.48);const ts=visibleEnemies(54).sort((x,y)=>y.maxHp-x.maxHp).slice(0,2+Math.floor(a.starfall/2));for(const e of ts){addVisual({type:"marker",x:e.x,y:e.y,r:35,life:.55,max:.55,color:C.spear,source:"starfall"});delayed.push({time:.55,type:"strike",x:e.x,y:e.y,r:38+a.starfall*4,damage:28+a.starfall*12,color:C.spear,source:"starfall",knock:110})}}
 if(a.overlord&&cd.overlord<=0){cd.overlord=Math.max(3.8,7.6-a.overlord*.65);const ang=facingAngle(),len=Math.max(W,H)*1.35,width=24+a.overlord*5;addVisual({type:"spearAura",x:player.x,y:player.y,a:ang,r:len,life:.42,max:.42,color:"#f1c36e",width});lineHit(player.x,player.y,player.x+Math.cos(ang)*len,player.y+Math.sin(ang)*len,width,55+a.overlord*25,"overlord",{knock:260,shake:11,color:"#f1c36e",life:.34});showMessage("무극패왕창 · 전방 발사",1)}
 if(a.arrowrain&&cd.arrowrain<=0){cd.arrowrain=Math.max(2.8,6-a.arrowrain*.43);const count=10+a.arrowrain*4;for(let i=0;i<count;i++){const x=player.x+(Math.random()-.5)*(W*.95),y=player.y-H*.58-Math.random()*100;projectile({x,y,vx:(Math.random()-.5)*70,vy:680,damage:13+a.arrowrain*7,r:3,pierce:1,shape:"arrow",color:C.bow,life:1.45,source:"arrowrain",trail:1})}}
 if(a.sunmoon&&cd.sunmoon<=0){cd.sunmoon=Math.max(2.5,5.7-a.sunmoon*.48);const t=nearest();if(t){const ang=Math.atan2(t.y-player.y,t.x-player.x),sun=Math.floor(elapsed)%2===0;projectile({vx:Math.cos(ang)*620,vy:Math.sin(ang)*620,damage:32+a.sunmoon*14,r:10,pierce:0,shape:sun?"sun":"moon",color:sun?"#f1bf55":"#b9d8ec",explode:70+a.sunmoon*8,elemental:true,life:1.7,source:"sunmoon",trail:1})}}
 if(a.thousand&&cd.thousand<=0){cd.thousand=Math.max(1.8,4.4-a.thousand*.4);const t=nearest(),base=t?Math.atan2(t.y-player.y,t.x-player.x):0,n=7+a.thousand*2;for(let i=0;i<n;i++){const ang=base+(i-(n-1)/2)*.09;projectile({vx:Math.cos(ang)*520,vy:Math.sin(ang)*520,damage:7+a.thousand*3,r:3,pierce:1,shape:"needle",poison:3+a.thousand*1.7,poisonTime:5,color:C.poison,source:"thousand"})}}
 if(a.miasma&&cd.miasma<=0){cd.miasma=Math.max(3.2,7-a.miasma*.52);const t=nearest(500)||{x:player.x,y:player.y};fields.push({type:"poison",source:"miasma",x:t.x,y:t.y,r:72+a.miasma*10,life:5+a.miasma*.45,tick:0,damage:4+a.miasma*2.7,color:C.poison});addVisual({type:"cloud",x:t.x,y:t.y,r:72+a.miasma*10,life:1,max:1,color:C.poison})}
 if(a.lifedeath&&cd.lifedeath<=0){cd.lifedeath=Math.max(4,8-a.lifedeath*.65);const r=175+a.lifedeath*18;aoe(player.x,player.y,r,22+a.lifedeath*11,"poison",{poison:9+a.lifedeath*4,poisonTime:7,color:"#c07acb",shake:7,vfxSource:"lifedeath"});player.hp=Math.min(player.maxHp,player.hp+5+a.lifedeath*3);showMessage("생사부",.9)}
 if(a.firedragon&&cd.firedragon<=0){cd.firedragon=Math.max(1.8,4.8-a.firedragon*.42);const t=nearest();if(t){const ang=Math.atan2(t.y-player.y,t.x-player.x);projectile({vx:Math.cos(ang)*430,vy:Math.sin(ang)*430,damage:20+a.firedragon*8,r:9,shape:"fire",explode:58+a.firedragon*7,elemental:true,color:"#db7048",source:"firedragon",trail:1})}}
 if(a.icearray){for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-player.x,e.y-player.y);if(d<115+a.icearray*13){e.slow=Math.min(e.slow,.78-a.icearray*.055);e.slowTime=.3;if(cd.icepulse<=0)damageEnemy(e,3+a.icearray*2,"elemental",{elemental:true,color:"#8fd2e8"})}}if(cd.icepulse<=0){cd.icepulse=.8;addVisual({type:"ring",x:player.x,y:player.y,r:115+a.icearray*13,life:.25,max:.25,color:"#8fd2e8",width:2,source:"icearray"})}}
 if(a.fivethunder&&cd.fivethunder<=0){cd.fivethunder=Math.max(3.2,7-a.fivethunder*.58);const ts=sampleRandom(enemies.filter(e=>!e.dead),5+a.fivethunder*2);for(const e of ts){addVisual({type:"lightning",x1:e.x+(Math.random()-.5)*20,y1:e.y-300,x2:e.x,y2:e.y,width:5,life:.23,max:.23,color:"#c6eaff"});damageEnemy(e,28+a.fivethunder*13,"elemental",{elemental:true,color:"#c6eaff",shake:4})}showMessage("오뢰정법",.8)}
 if(a.whirlwind&&cd.whirlwind<=0){cd.whirlwind=Math.max(.75,1.8-a.whirlwind*.16);aoe(player.x,player.y,78+a.whirlwind*9,10+a.whirlwind*6,"whirlwind",{knock:85,color:C.saber});addVisual({type:"spiral",x:player.x,y:player.y,r:83+a.whirlwind*9,life:.28,max:.28,color:C.saber})}
 if(a.mountain&&cd.mountain<=0){cd.mountain=Math.max(2.1,5-a.mountain*.42);const t=nearest();if(t){const ang=Math.atan2(t.y-player.y,t.x-player.x),len=240+a.mountain*24;lineHit(player.x,player.y,player.x+Math.cos(ang)*len,player.y+Math.sin(ang)*len,25+a.mountain*3,38+a.mountain*15,"mountain",{knock:220,shake:9,color:"#d57d5d",life:.28})}}
 if(a.demon&&cd.demon<=0){cd.demon=Math.max(4,8.5-a.demon*.7);player.hp=Math.max(1,player.hp-(7+a.demon));aoe(player.x,player.y,190+a.demon*22,50+a.demon*22,"demon",{knock:300,shake:14,color:"#a82e35",width:9});addVisual({type:"cross",x:player.x,y:player.y,r:200+a.demon*22,life:.45,max:.45,color:"#a82e35"});showMessage("천마군림도",1)}
 if(a.moonchain&&cd.moonchain<=0){cd.moonchain=Math.max(1.7,4.6-a.moonchain*.4);let from={x:player.x,y:player.y},used=[];const chains=2+a.moonchain*2,range=190+a.moonchain*28;for(let i=0;i<chains;i++){const t=nearest(range,from.x,from.y,used);if(!t)break;const ang=Math.atan2(t.y-from.y,t.x-from.x),width=6+a.moonchain*.75;lineHit(from.x,from.y,t.x,t.y,width,13+a.moonchain*6.2,"moonchain",{shake:1.6,color:i%2?"#c7d8ff":"#f0eaff",life:.13+i*.008});addVisual({type:"slashArc",x:t.x,y:t.y,a:ang+(i%2?1:-1)*.7,r:24+a.moonchain*4,life:.2,max:.2,color:"#e9e7ff",width:2+a.moonchain*.3});used.push(t);from=t}if(used.length)showMessage(`월영연참 · ${used.length}연쇄`,.65)}
 if(a.zanshin&&Math.hypot(move.x,move.y)>.3){cd.zanshinDrop=(cd.zanshinDrop||0)-dt;if(cd.zanshinDrop<=0){cd.zanshinDrop=Math.max(.55,1.35-a.zanshin*.12);const x=player.x,y=player.y;addVisual({type:"afterimage",x,y,r:18,life:.65,max:.65,color:C.katana});delayed.push({time:.55,type:"aoe",x,y,r:58+a.zanshin*5,damage:12+a.zanshin*7,color:C.katana,source:"zanshin",knock:60})}}
 if(a.nameless&&cd.nameless<=0){cd.nameless=Math.max(3.7,8-a.nameless*.7);for(let i=0;i<8+a.nameless*3;i++){const ang=Math.random()*Math.PI*2,off=(Math.random()-.5)*260,x1=player.x+Math.cos(ang+Math.PI/2)*off-Math.cos(ang)*500,y1=player.y+Math.sin(ang+Math.PI/2)*off-Math.sin(ang)*500,x2=x1+Math.cos(ang)*1000,y2=y1+Math.sin(ang)*1000;lineHit(x1,y1,x2,y2,8+a.nameless,17+a.nameless*9,"nameless",{shake:3,color:"#ededff",life:.16})}showMessage("무명신풍류",.9)}
 if(a.hundredstep&&cd.hundredstep<=0){cd.hundredstep=Math.max(1.3,3.5-a.hundredstep*.32);const t=nearest();if(t){const ang=Math.atan2(t.y-player.y,t.x-player.x);projectile({vx:Math.cos(ang)*620,vy:Math.sin(ang)*620,damage:22+a.hundredstep*9,r:13,pierce:1+Math.floor(a.hundredstep/2),shape:"fist",knock:180,color:"#dfbc7c",source:"hundredstep",trail:1})}}
 if(a.taijifist&&cd.taijifist<=0){cd.taijifist=Math.max(1.8,4.6-a.taijifist*.4);aoe(player.x,player.y,105+a.taijifist*12,8+a.taijifist*5,"taijifist",{knock:280+a.taijifist*20,color:"#e0cf9f",width:3});addVisual({type:"yin",x:player.x,y:player.y,r:62+a.taijifist*6,life:.55,max:.55,color:"#e0cf9f"})}
 if(a.dragonreturn&&cd.dragonreturn<=0){cd.dragonreturn=Math.max(3,7-a.dragonreturn*.58);const t=nearest();if(t){const ang=Math.atan2(t.y-player.y,t.x-player.x),len=Math.max(W,H)*1.1;lineHit(player.x,player.y,player.x+Math.cos(ang)*len,player.y+Math.sin(ang)*len,28+a.dragonreturn*4,48+a.dragonreturn*20,"dragonreturn",{knock:340,shake:12,color:"#efc55f",life:.4});addVisual({type:"dragon",x:player.x,y:player.y,a:ang,r:len,life:.52,max:.52,color:"#efc55f"});showMessage("항룡유회",1)}}
}

function performDodge(){if(state!=="playing"||player.dodgeCooldown>0||player.dodgeTimer>0)return;initAudio();const a=facingAngle(),distance=(115+player.shrinkStep*12)*player.dodgeDistanceMul,duration=Math.max(.14,player.dodgeDuration),sx=player.x,sy=player.y;player.dodgeTimer=duration;player.dodgeVx=Math.cos(a)*distance/duration;player.dodgeVy=Math.sin(a)*distance/duration;player.dodgeCooldown=Math.max(1.05,4.2*player.dodgeCooldownMul);player.invuln=Math.max(player.invuln,duration+player.dodgeInvuln);player.metrics.dodges++;if(player.cloudStep)player.speedBuff=1.4+.25*player.cloudStep;if(player.lingbo)aoe(sx,sy,34+player.lingbo*12,10+player.lingbo*9,"footwork",{color:"#b9e6df",knock:80});if(player.shrinkStep)lineHit(sx,sy,sx+Math.cos(a)*distance,sy+Math.sin(a)*distance,8+player.shrinkStep*3,9+player.shrinkStep*8,"footwork",{color:"#d8f5ff",life:.24});addVisual({type:"afterimage",x:sx,y:sy,r:18+player.lingbo*3,life:.36,max:.36,color:"#b9e6df"});addVisual({type:"line",x1:sx,y1:sy,x2:sx+Math.cos(a)*distance,y2:sy+Math.sin(a)*distance,width:5,life:.2,max:.2,color:"#d8f5ff"});GameAudio.playSFX("dodge")}
function updateInput(){
  const settings=account.settings||{};
  let x=0,y=0;
  if(keys[settings.keyMoveLeft||"KeyA"]||keys.ArrowLeft)x--;
  if(keys[settings.keyMoveRight||"KeyD"]||keys.ArrowRight)x++;
  if(keys[settings.keyMoveUp||"KeyW"]||keys.ArrowUp)y--;
  if(keys[settings.keyMoveDown||"KeyS"]||keys.ArrowDown)y++;
  if(pointer.active){
    const dx=pointer.x-pointer.ox,dy=pointer.y-pointer.oy,l=Math.hypot(dx,dy),max=44*(settings.joystickSize||1),m=Math.min(max,l),nx=l?dx/l:0,ny=l?dy/l:0;
    x=nx*m/max;y=ny*m/max;
    ui.stick.style.transform=`translate(calc(-50% + ${nx*m}px),calc(-50% + ${ny*m}px))`;
  }
  const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}move.x=x;move.y=y;
}

function update(dt){if(state!=="playing")return;elapsed+=dt;if(messageTimer>0&&(messageTimer-=dt)<=0)ui.message.classList.remove("show");screenShake=Math.max(0,screenShake-dt*28);flash=Math.max(0,flash-dt*3);player.invuln=Math.max(0,player.invuln-dt);player.dodgeCooldown=Math.max(0,player.dodgeCooldown-dt);player.speedBuff=Math.max(0,player.speedBuff-dt);player.metrics.noHit+=dt;player.metrics.maxNoHit=Math.max(player.metrics.maxNoHit,player.metrics.noHit);if(player.hp/player.maxHp<.35)player.metrics.lowHpTime+=dt;updateInput();if(Math.hypot(move.x,move.y)>.08){player.facing=Math.atan2(move.y,move.x);player.moving=true}else player.moving=false;if(player.dodgeTimer>0){player.dodgeTimer-=dt;player.x+=player.dodgeVx*dt;player.y+=player.dodgeVy*dt}else{const sm=player.speedBuff>0?1.2+.06*player.cloudStep:1;player.x+=move.x*player.speed*sm*dt;player.y+=move.y*player.speed*sm*dt;}player.regenTimer-=dt;if(player.regen&&player.regenTimer<=0){player.regenTimer=8;player.hp=Math.min(player.maxHp,player.hp+player.regen)}player.fireTimer-=dt;if(player.fireTimer<=0){fireBasic();player.fireTimer*=player.attackSpeedMul}tickArts(dt);spawnTimer-=dt;const diff=difficultyDefs[selectedDifficulty],target=Math.min(diff.maxEnemies,(20+elapsed*1.02)*diff.spawn);if(spawnTimer<=0&&enemies.length<target){spawnTimer=Math.max(.065,(.48-elapsed*.0022)/diff.spawn);const r=Math.random();let type="bandit";if(elapsed>90&&r<.12)type="assassin";else if(elapsed>58&&r<.27)type="master";else if(elapsed>35&&r<.43)type="brute";else if(elapsed>12&&r<.65)type="spear";spawnAround(type)}while(elapsed>=nextMiniBossAt&&nextMiniBossAt<finalBossAt){spawnMiniBoss();nextMiniBossAt+=60}if(!bossSpawned&&elapsed>=finalBossAt)spawnBoss();updateSpecialPatterns(dt);updateProjectiles(dt);updateEnemies(dt);updateGems(dt);updateChests(dt);updateHazards(dt);updateFields(dt);updateDelayed(dt);updateParticles(dt);updateVisuals(dt);enemies=enemies.filter(e=>!e.dead);for(const p of projectiles)if(!(p.life>0&&p.hits<=p.pierce))GamePools.projectile.release(p);projectiles=projectiles.filter(p=>p.life>0&&p.hits<=p.pierce);gems=gems.filter(g=>!g.dead);chests=chests.filter(c=>!c.dead);hazards=hazards.filter(h=>!h.dead);for(const p of particles)if(p.life<=0)GamePools.particle.release(p);particles=particles.filter(p=>p.life>0);visuals=visuals.filter(v=>v.life>0);fields=fields.filter(f=>f.life>0);delayed=delayed.filter(d=>d.time>0);checkHidden();updateHud();if(elapsed>=runDuration&&state==="playing"&&boss)endGame(false,"time")}
function updateSpecialPatterns(dt){for(const e of enemies){if(e.dead||!["midboss","boss"].includes(e.type))continue;e.special=(e.special||0)-dt;if(e.type==="midboss"&&e.special<=0){if(e.subtype==="blackblade"){e.special=4.2;prepareCharge(e,660,e.damage*1.28);showMessage("흑도객 · 흑풍돌진",.8)}else if(e.subtype==="poisonhand"){e.special=4.8;hazards.push({type:"blast",x:player.x,y:player.y,r:98,time:.88,damage:e.damage,color:"#9d60ae",dead:false});showMessage("독수귀 · 독혈장",.8)}else{e.special=5.1;hazards.push({type:"blast",x:e.x,y:e.y,r:130,time:.7,damage:e.damage*1.2,color:"#c59262",dead:false});for(let i=0;i<2;i++){const a=Math.random()*Math.PI*2;spawnEnemy("brute",e.x+Math.cos(a)*65,e.y+Math.sin(a)*65)}showMessage("철탑승 · 진각",.8)}}if(e.type==="boss"){const d=difficultyDefs[selectedDifficulty];e.cross=e.cross??(d.rank>=2?4.6:999);e.puddle=e.puddle??(d.rank>=2?5.8:999);e.phase3Burst=e.phase3Burst||false;if(!e.phase2&&e.hp/e.maxHp<=.7){e.phase2=true;e.speed*=1.14;e.damage*=1.14;e.summon=.8;e.blast=.8;if(e.dash)e.dash=.95;if(e.orbs)e.orbs=.9;e.cross=Math.min(e.cross,3.7);e.puddle=Math.min(e.puddle,4.7);showMessage("혈마가 혈해마공을 펼친다",2.2);screenShake=14;addVisual({type:"ring",x:e.x,y:e.y,r:170,life:.7,max:.7,color:"#ff8b88",width:10})}if(d.rank>=2&&!e.phase3&&e.hp/e.maxHp<=.35){e.phase3=true;e.speed*=1.16;e.damage*=1.18;e.summon=.5;e.blast=.45;e.dash=.55;e.orbs=.65;e.cross=1.6;e.puddle=2.9;if(!e.phase3Burst){e.phase3Burst=true;for(let i=0;i<Math.max(1,d.rank-1);i++)spawnMiniBoss()}showMessage("혈마 최종변화 · 혈해천마",2.5);screenShake=18;addVisual({type:"ring",x:e.x,y:e.y,r:220,life:.85,max:.85,color:"#ff6b6b",width:13})}
 e.summon-=dt;e.blast-=dt;if(e.dash)e.dash-=dt;if(e.orbs)e.orbs-=dt;if(e.cross)e.cross-=dt;if(e.puddle)e.puddle-=dt;
 if(e.summon<=0){e.summon=d.summon*(e.phase3?.78:e.phase2?.85:1);const n=5+d.rank*2+(e.phase3?2:0);for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2;spawnEnemy(i%2?"assassin":"spear",e.x+Math.cos(a)*82,e.y+Math.sin(a)*82)}showMessage("혈마 · 혈교 사도 소환",1)}
 if(e.blast<=0){e.blast=d.blast*(e.phase3?.72:e.phase2?.82:1);const baseR=94+d.rank*14;hazards.push({type:"blast",x:player.x,y:player.y,r:baseR,time:.82,damage:e.damage,color:"#b6323a",dead:false});if(d.rank>=2){const ang=Math.random()*Math.PI*2;hazards.push({type:"blast",x:player.x+Math.cos(ang)*92,y:player.y+Math.sin(ang)*92,r:baseR*.72,time:.72,damage:e.damage*.92,color:"#cc454d",dead:false});hazards.push({type:"blast",x:player.x-Math.cos(ang)*92,y:player.y-Math.sin(ang)*92,r:baseR*.72,time:.72,damage:e.damage*.92,color:"#cc454d",dead:false})}showMessage("혈마 · 혈폭장",.8)}
 if(d.dash>0&&e.dash<=0){e.dash=d.dash*(e.phase3?.72:e.phase2?.85:1);prepareCharge(e,e.phase3?880:780,e.damage*(e.phase3?1.28:1.16));showMessage(e.phase3?"혈마 · 혈영연진":"혈마 · 혈영신법",.9)}
 if(d.orbs>0&&e.orbs<=0){e.orbs=d.orbs*(e.phase3?.74:e.phase2?.86:1);const n=(e.phase3?10:e.phase2?8:5)+d.rank*2;for(let i=0;i<n;i++){const a=i*Math.PI*2/n;hazards.push({type:"orb",x:e.x,y:e.y,vx:Math.cos(a)*(e.phase3?210:185),vy:Math.sin(a)*(e.phase3?210:185),r:8,life:e.phase3?4.8:4.1,damage:e.damage*.72,color:"#c23b46",dead:false,homing:e.phase3&&i%2===0?1.8:0})}showMessage("혈마 · 혈옥산화",.8)}
 if(d.rank>=2&&e.cross<=0){e.cross=e.phase3?2.2:4.4;hazards.push({type:"cross",x:player.x,y:player.y,w:e.phase3?46:38,time:e.phase3?.62:.7,damage:e.damage*(e.phase3?1.08:.92),color:e.phase3?"#ff6a72":"#df5a63",dead:false});showMessage(e.phase3?"혈마 · 천열십자":"혈마 · 십자혈열참",.85)}
 if(d.rank>=2&&e.puddle<=0){e.puddle=e.phase3?3.4:5.7;const count=e.phase3?3:2;for(let i=0;i<count;i++){const ang=Math.random()*Math.PI*2,dist=60+Math.random()*120;hazards.push({type:"puddle",x:player.x+Math.cos(ang)*dist,y:player.y+Math.sin(ang)*dist,r:e.phase3?62:50,life:e.phase3?5.2:4.2,damage:e.damage*.45,tick:.3,color:e.phase3?"rgba(136,27,36,.58)":"rgba(110,20,30,.52)",dead:false})}showMessage("혈마 · 혈지장",.8)}
 }}}
function prepareCharge(e,speed,damage){const a=Math.atan2(player.y-e.y,player.x-e.x);e.chargeDelay=.44;e.chargeTime=.62;e.chargeVx=Math.cos(a)*speed;e.chargeVy=Math.sin(a)*speed;e.chargeDamage=damage||e.damage;addVisual({type:"line",x1:e.x,y1:e.y,x2:e.x+Math.cos(a)*500,y2:e.y+Math.sin(a)*500,width:4,life:.44,max:.44,color:"#d35a5a"})}
function updateProjectiles(dt){for(const p of projectiles){if(p.homing){const t=nearest(260,p.x,p.y);if(t){const sp=Math.hypot(p.vx,p.vy),ta=Math.atan2(t.y-p.y,t.x-p.x),ca=Math.atan2(p.vy,p.vx),da=Math.atan2(Math.sin(ta-ca),Math.cos(ta-ca)),na=ca+da*Math.min(1,p.homing*dt);p.vx=Math.cos(na)*sp;p.vy=Math.sin(na)*sp}}p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.trail&&Math.random()<.55)particle(p.x,p.y,p.color,20,1);for(const e of GameSpatial.queryCircle(p.x,p.y,p.r+72)){if(e.dead||p.hits>p.pierce)break;const rr=e.r+p.r;if((e.x-p.x)**2+(e.y-p.y)**2<rr*rr){damageEnemy(e,p.damage,p.source,{poison:p.poison,poisonTime:p.poisonTime,knock:p.knock,elemental:p.elemental,color:p.color,slow:player.forgedWeapon&&player.forgedWeapon.ability==="ice"?.84:0,slowTime:1.3,distance:Math.hypot(e.x-player.x,e.y-player.y)});if(player.forgedWeapon&&player.forgedWeapon.ability==="fire"&&Math.random()<.08)aoe(p.x,p.y,34,Math.max(4,p.damage*.32),"forgefire",{color:"#ef8052",elemental:true,shake:2});if(player.forgedWeapon&&player.forgedWeapon.ability==="thunder"&&Math.random()<.08){const z=nearest(125,e.x,e.y,[e]);if(z){addVisual({type:"lightning",x1:e.x,y1:e.y,x2:z.x,y2:z.y,width:2,life:.13,max:.13,color:"#8bd5ff"});damageEnemy(z,p.damage*.28,"forgethunder",{elemental:true,color:"#8bd5ff"})}}if(p.shape==="spear"&&p.hits>0)player.metrics.pierceHits++;if(p.knock){const d=Math.hypot(e.x-p.x,e.y-p.y)||1;e.pushX+=(e.x-p.x)/d*p.knock;e.pushY+=(e.y-p.y)/d*p.knock;player.metrics.knockbacks++}p.hits++;if(p.explode){aoe(p.x,p.y,p.explode,p.damage*.72,p.source,{elemental:p.elemental,color:p.color,shake:5});p.hits=p.pierce+1}}}}}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.orbitHit=Math.max(0,e.orbitHit-dt);if(e.poisonTime>0){e.poisonTime-=dt;e.poisonTick-=dt;if(e.poisonTick<=0){e.poisonTick=.55;damageEnemy(e,e.poison*.55,"poison",{color:C.poison})}}if(e.slowTime>0)e.slowTime-=dt;else e.slow=1;const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(e.chargeDelay>0){e.chargeDelay-=dt}else if(e.chargeTime>0){e.chargeTime-=dt;e.x+=e.chargeVx*dt;e.y+=e.chargeVy*dt}else{const sp=e.speed*e.slow*(e.type==="boss"&&d<130?.55:1);e.x+=(dx/d*sp+e.pushX)*dt;e.y+=(dy/d*sp+e.pushY)*dt}e.pushX*=Math.pow(.025,dt);e.pushY*=Math.pow(.025,dt);if(d<(player.hitRadius||player.r)+e.r&&player.invuln<=0)hurtPlayer(e.chargeTime>0?(e.chargeDamage||e.damage):e.damage)}}
function updateGems(dt){for(const g of gems){const dx=player.x-g.x,dy=player.y-g.y,d=Math.hypot(dx,dy)||1;if(d<player.pickup*2.2){const pull=190+(player.pickup*2.2-d)*4;g.vx+=dx/d*pull*dt;g.vy+=dy/d*pull*dt}g.vx*=Math.pow(.12,dt);g.vy*=Math.pow(.12,dt);g.x+=g.vx*dt;g.y+=g.vy*dt;if(d<(player.hitRadius||player.r)+g.r+5){g.dead=true;if(g.kind==="heal"||g.heal){player.hp=Math.min(player.maxHp,player.hp+(g.heal||15));showMessage("영약을 복용했다",.9)}else if(g.kind==="gold"){account.gold+=g.value;player.runGold+=g.value}else if(g.kind==="ore"){const k=oreKey(g.type,g.grade);account.ores[k]=(account.ores[k]||0)+1;player.runOres[k]=(player.runOres[k]||0)+1;showMessage(`${gradeName(g.grade)} ${oreTypes[g.type].name} 획득`,1.1)}else gainXp(g.value);refreshAccountUI();GameAudio.playUI(g.kind==="ore"?"ore-pickup":g.kind==="gold"?"gold-pickup":g.kind==="heal"||g.heal?"heal-pickup":"pickup")}}}

function updateChests(dt){if(state!=="playing")return;for(const c of chests){c.bob+=dt*3;const d=Math.hypot(player.x-c.x,player.y-c.y);if(d<player.r+c.r+8){c.dead=true;player.chestsOpened++;openAugmentChoice();break}}}
function updateHazards(dt){for(const h of hazards){if(h.dead)continue;if(h.type==="blast"){h.time-=dt;if(h.time<=0){if(Math.hypot(player.x-h.x,player.y-h.y)<h.r+player.r)hurtPlayer(h.damage);addVisual({type:"ring",x:h.x,y:h.y,r:h.r,life:.35,max:.35,color:h.color||"#b6323a",width:7});particle(h.x,h.y,h.color||"#b6323a",120,12);h.dead=true}}else if(h.type==="orb"){if(h.homing){const ta=Math.atan2(player.y-h.y,player.x-h.x),ca=Math.atan2(h.vy,h.vx),sp=Math.hypot(h.vx,h.vy)||1,da=Math.atan2(Math.sin(ta-ca),Math.cos(ta-ca));const na=ca+da*Math.min(1,h.homing*dt);h.vx=Math.cos(na)*sp;h.vy=Math.sin(na)*sp}h.x+=h.vx*dt;h.y+=h.vy*dt;h.life-=dt;if(Math.hypot(player.x-h.x,player.y-h.y)<player.r+h.r){hurtPlayer(h.damage);h.dead=true}else if(h.life<=0)h.dead=true}else if(h.type==="puddle"){h.life-=dt;h.tick-=dt;if(h.tick<=0){h.tick=.32;if(Math.hypot(player.x-h.x,player.y-h.y)<h.r+player.r)hurtPlayer(h.damage)}}else if(h.type==="cross"){h.time-=dt;if(h.time<=0){const w=h.w||38;if(Math.abs(player.x-h.x)<w+player.r||Math.abs(player.y-h.y)<w+player.r)hurtPlayer(h.damage);addVisual({type:"line",x1:h.x-900,y1:h.y,x2:h.x+900,y2:h.y,width:w*1.2,life:.18,max:.18,color:h.color||"#df5a63"});addVisual({type:"line",x1:h.x,y1:h.y-900,x2:h.x,y2:h.y+900,width:w*1.2,life:.18,max:.18,color:h.color||"#df5a63"});h.dead=true}}}}
function updateFields(dt){for(const f of fields){f.life-=dt;f.tick-=dt;if(f.tick<=0){f.tick=.55;for(const e of GameSpatial.queryCircle(f.x,f.y,f.r+64)){if(e.dead)continue;if(Math.hypot(e.x-f.x,e.y-f.y)<f.r+e.r)damageEnemy(e,f.damage,"poison",{poison:f.damage*.8,poisonTime:2.5,color:f.color})}}}}
function updateDelayed(dt){for(const d of delayed){d.time-=dt;if(d.time<=0){if(d.type==="strike")aoe(d.x,d.y,d.r,d.damage,d.source,{color:d.color,knock:d.knock||0,shake:5});else if(d.type==="aoe")aoe(d.x,d.y,d.r,d.damage,d.source,{color:d.color,knock:d.knock||0,shake:4});else if(d.type==="katanaSlash"){const px=player.x+Math.cos(d.a+Math.PI/2)*d.side,py=player.y+Math.sin(d.a+Math.PI/2)*d.side,x2=px+Math.cos(d.a)*d.len,y2=py+Math.sin(d.a)*d.len;lineHit(px,py,x2,y2,d.width,d.damage,"basic",{shake:3+d.index*.55,color:d.color,life:.15});addVisual({type:"slashArc",x:px+Math.cos(d.a)*(40+d.index*4),y:py+Math.sin(d.a)*(40+d.index*4),a:d.a,r:d.arc,life:.18,max:.18,color:d.color,width:d.arcWidth});addVisual({type:"afterimage",x:player.x-Math.cos(d.a)*(5+d.index*2),y:player.y-Math.sin(d.a)*(5+d.index*2),r:16+d.index,life:.13,max:.13,color:d.color})}}}}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.08,dt);p.vy*=Math.pow(.08,dt);p.life-=dt}}
function updateVisuals(dt){for(const v of visuals)v.life-=dt}
function updateHud(){ui.hpFill.style.width=Math.max(0,player.hp/player.maxHp*100)+"%";ui.xpFill.style.width=Math.max(0,player.xp/player.xpNeed*100)+"%";ui.levelText.textContent="경지 "+player.level;ui.timeText.textContent=fmtTime(runDuration-elapsed);ui.killText.textContent="격파 "+player.kills;ui.goldHud.textContent=`금자 ${Math.floor(account.gold||0)}`;ui.oreHud.textContent=`광석 ${totalOres()}`;const cd=Math.max(0,player.dodgeCooldown);ui.dodgeHud.textContent=cd>0?`보법 ${cd.toFixed(1)}초`:"보법 준비";ui.dodgeCd.textContent=cd>0?cd.toFixed(1)+"초":"준비";ui.dodgeBtn.classList.toggle("cooling",cd>0);if(boss&&!boss.dead){ui.bossFill.style.width=Math.max(0,boss.hp/boss.maxHp*100)+"%";ui.bossText.textContent=Math.ceil(boss.hp)+" / "+Math.ceil(boss.maxHp)}}
