"use strict";
// Pixel render replacements. Character bodies never rotate.
drawPlayer=function(){if(player.invuln>0&&Math.floor(player.invuln*14)%2===0)return;const dir=facingDir(),frame=player.moving?Math.floor(elapsed*8)%2:0;player.dir=dir;ctx.save();ctx.imageSmoothingEnabled=false;drawPixelHero(ctx,W/2,H/2,selectedWeapon,dir,frame,3*mobileCameraScale());ctx.fillStyle="#dff4ff";ctx.font="bold 10px system-ui";ctx.textAlign="center";ctx.fillText({up:"▲",down:"▼",left:"◀",right:"▶"}[dir],W/2,H/2-37);if(player.shield>0){ctx.strokeStyle="rgba(180,235,255,.7)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(W/2,H/2,27,0,Math.PI*2);ctx.stroke()}ctx.restore()};
drawEnemies=function(){for(const e of enemies){if(e.dead)continue;const s=ws(e.x,e.y);if(s.x<-100||s.x>W+100||s.y<-100||s.y>H+100)continue;drawPixelEnemy(ctx,e,s.x,s.y);if(e.poisonTime>0){ctx.strokeStyle="rgba(174,110,194,.8)";ctx.lineWidth=2;ctx.strokeRect(s.x-e.r,s.y-e.r,e.r*2,e.r*2)}if(e.type==="boss"||e.type==="midboss"||e.hp<e.maxHp){const bw=Math.max(28,e.r*2.2);ctx.fillStyle="rgba(0,0,0,.55)";ctx.fillRect(s.x-bw/2,s.y-e.r-17,bw,5);ctx.fillStyle=e.type==="boss"?"#b8473e":e.type==="midboss"?"#d98f4b":"#d9b95f";ctx.fillRect(s.x-bw/2,s.y-e.r-17,bw*Math.max(0,e.hp/e.maxHp),5);if(e.type==="midboss"){ctx.fillStyle="#f2d895";ctx.font="10px system-ui";ctx.textAlign="center";ctx.fillText(e.bossName,s.x,s.y-e.r-22)}}}}
function drawBossArrows(){for(const e of enemies.filter(x=>!x.dead&&(x.type==="boss"||x.type==="midboss"))){const s=ws(e.x,e.y),margin=55;if(s.x>margin&&s.x<W-margin&&s.y>margin&&s.y<H-margin)continue;const dx=s.x-W/2,dy=s.y-H/2,a=Math.atan2(dy,dx),rx=W/2-margin,ry=H/2-margin,t=Math.min(rx/Math.max(1,Math.abs(Math.cos(a))),ry/Math.max(1,Math.abs(Math.sin(a)))),x=W/2+Math.cos(a)*t,y=H/2+Math.sin(a)*t;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle=e.type==="boss"?"#ff6e66":"#f0c466";ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-9,-10);ctx.lineTo(-5,0);ctx.lineTo(-9,10);ctx.closePath();ctx.fill();ctx.strokeStyle="#1b120e";ctx.stroke();ctx.rotate(-a);ctx.fillStyle="#fff3c9";ctx.font="bold 10px system-ui";ctx.textAlign="center";ctx.fillText(e.type==="boss"?"혈마":e.bossName,0,24);ctx.restore()}}
const baseDraw=draw;draw=function(){const ss=screenShake;screenShake=ss*(account.settings?.shake??1);baseDraw();screenShake=ss;if(state==="playing"||state==="paused")drawBossArrows()};

function checkAchievements(){ensureV6Account();let changed=false;for(const a of achievementDefs){if(account.achievements[a.id])continue;if(a.value()>=a.goal){account.achievements[a.id]=true;account.gold+=a.reward;changed=true;showMessage(`업적 달성 · ${a.name} (+${a.reward} 금자)`,2.5)}}if(changed)saveAccountData()}
function renderAchievements(){ensureV6Account();checkAchievements();ui.achievementList.innerHTML=achievementDefs.map(a=>{const v=Math.min(a.goal,a.value()),done=!!account.achievements[a.id];return`<div class="collection-card ${done?"unlocked":""}"><b>${done?"✓ ":""}${a.name}</b><p>${a.desc}<br>보상 ${a.reward} 금자</p><div class="achievement-progress"><span style="width:${v/a.goal*100}%"></span></div><p>${v}/${a.goal}</p></div>`}).join("")}
