"use strict";
function loadAccountData(){try{const a=JSON.parse(localStorage.getItem("murimAccountV1")||"null");if(a)account=Object.assign(account,a)}catch(_){}account.ores=account.ores||{};account.weapons=account.weapons||[];account.equipped=account.equipped||{};refreshAccountUI()}
function saveAccountData(){try{localStorage.setItem("murimAccountV1",JSON.stringify(account))}catch(_){}refreshAccountUI()}
function oreKey(type,grade){return `${type}:${grade}`}
function totalOres(){return Object.values(account.ores).reduce((a,b)=>a+(b||0),0)}
function gradeName(id){return (gradeDefs.find(g=>g.id===id)||gradeDefs[0]).name}
function gradeIndex(id){return Math.max(0,gradeDefs.findIndex(g=>g.id===id))}
function refreshAccountUI(){if(!ui.accountGold)return;ui.accountGold.textContent=Math.floor(account.gold||0);ui.accountOre.textContent=totalOres();ui.accountWeapons.textContent=account.weapons.length;ui.goldHud.textContent=`금자 ${Math.floor(account.gold||0)}`;ui.oreHud.textContent=`광석 ${totalOres()}`}

const player={x:0,y:0,r:14,hp:100,maxHp:100,speed:170,level:1,xp:0,xpNeed:18,kills:0,pickup:78,damageMul:1,eliteDamageMul:1,damageReduction:0,attackSpeedMul:1,xpMul:1,cooldownRate:1,killHeal:0,regen:0,regenTimer:8,invuln:0,fireTimer:0,projectileBonus:0,pierceBonus:0,areaMul:1,critChance:.03,critDamage:1.5,projectileSpeedMul:1,poisonMul:1,dodgeCooldown:0,dodgeCooldownMul:1,dodgeDistanceMul:1,dodgeTimer:0,dodgeDuration:.18,dodgeInvuln:.2,dodgeVx:0,dodgeVy:0,cloudStep:0,lingbo:0,shrinkStep:0,speedBuff:0,arts:{},universal:Object.fromEntries(universal.map(u=>[u.id,0])),augments:{},chestsOpened:0,midBossKills:0,cooldowns:{},hiddenReady:{},hiddenNotified:{},runGold:0,runOres:{},forgedWeapon:null,metrics:{kills:0,rangedKills:0,closeKills:0,poisonKills:0,elementalKills:0,pierceHits:0,brutes:0,elites:0,damageTaken:0,lowHpTime:0,noHit:0,maxNoHit:0,knockbacks:0,dodges:0}};

function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0)}
function fmtTime(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function initAudio(){if(typeof GameAudio!=="undefined")GameAudio.unlock()}
function showMessage(t,s=1.6){ui.message.textContent=t;ui.message.classList.add("show");messageTimer=s}
function loadRecords(){let r={};try{r=JSON.parse(localStorage.getItem("murimSurvivorV2")||"{}") }catch(_){}ui.bestKills.textContent=r.kills||0;ui.bestLevel.textContent=r.level||1;ui.bestTime.textContent=fmtTime(r.time||0);refreshAccountUI()}
function saveRecords(){let r={};try{r=JSON.parse(localStorage.getItem("murimSurvivorV2")||"{}") }catch(_){}r={kills:Math.max(r.kills||0,player.kills),level:Math.max(r.level||1,player.level),time:Math.max(r.time||0,elapsed)};try{localStorage.setItem("murimSurvivorV2",JSON.stringify(r))}catch(_){}saveAccountData();loadRecords()}

function oreOptions(select){const current=select.value,entries=Object.entries(account.ores).filter(([,n])=>n>0);select.innerHTML='<option value="">광석 선택</option>'+entries.map(([k,n])=>{const [t,g]=k.split(":"),gd=gradeDefs.find(x=>x.id===g);return `<option value="${k}">[${gd.name}] ${oreTypes[t].name} ×${n}</option>`}).join("");if(entries.some(([k])=>k===current))select.value=current}
function refreshForge(){refreshAccountUI();ui.forgeWeapon.innerHTML=Object.entries(weaponDefs).map(([id,w])=>`<option value="${id}">${w.icon} ${w.name}</option>`).join("");const selects=[$("oreSlot1"),$("oreSlot2"),$("oreSlot3")];selects.forEach(oreOptions);ui.oreInventory.innerHTML=Object.entries(account.ores).filter(([,n])=>n>0).map(([k,n])=>{const[t,g]=k.split(":"),gd=gradeDefs.find(x=>x.id===g);return `<span class="ore-pill rarity-${g}">${gd.name} ${oreTypes[t].name} ×${n}</span>`}).join("")||'<span class="desc">보유 광석이 없다. 엘리트 몬스터를 처치하시오.</span>';renderWeaponInventory();updateForgePreview()}
function selectedOres(){return [$("oreSlot1").value,$("oreSlot2").value,$("oreSlot3").value].filter(Boolean)}
function updateForgePreview(){const arr=selectedOres();if(arr.length<3){ui.forgePreview.textContent="서로 다른 광석도 조합할 수 있다. 같은 종류를 모으면 고유능력이 강화된다.";return}const indexes=arr.map(k=>gradeIndex(k.split(":")[1])),avg=indexes.reduce((a,b)=>a+b,0)/3,sameGrade=new Set(arr.map(k=>k.split(":")[1])).size===1,sameType=new Set(arr.map(k=>k.split(":")[0])).size===1,cost=50+indexes.reduce((a,b)=>a+b,0)*35,base=Math.min(6,Math.floor(avg)+(sameGrade?0:0));ui.forgePreview.innerHTML=`예상 등급 <b class="rarity-${gradeDefs[base].id}">${gradeDefs[base].name}</b>${sameGrade?" · 상위 등급 확률 증가":""}<br>조합 궁합 ${sameType?"대성공":"보통"} · 필요 금자 ${cost}`}
function forgeWeapon(){const arr=selectedOres();if(arr.length<3){ui.forgePreview.textContent="광석 세 개를 모두 선택해야 한다.";return}const need={};arr.forEach(k=>need[k]=(need[k]||0)+1);for(const [k,n] of Object.entries(need))if((account.ores[k]||0)<n){ui.forgePreview.textContent="같은 광석의 보유 수량이 부족하다.";return}const idx=arr.map(k=>gradeIndex(k.split(":")[1])),types=arr.map(k=>k.split(":")[0]),sameGrade=new Set(idx).size===1,sameType=new Set(types).size===1,quench=$("quench").value,cost=50+idx.reduce((a,b)=>a+b,0)*35;if(account.gold<cost){ui.forgePreview.textContent=`금자가 부족하다. 필요 금자 ${cost}`;return}account.gold-=cost;for(const[k,n]of Object.entries(need))account.ores[k]-=n;let gi=Math.min(6,Math.floor(idx.reduce((a,b)=>a+b,0)/3));const upgradeChance=(sameGrade?.22:0)+(sameType?.1:0)+(quench==="elixir"?.08:0);if(gi<6&&Math.random()<upgradeChance)gi++;const counts={};types.forEach(t=>counts[t]=(counts[t]||0)+1);const ability=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0],wid=ui.forgeWeapon.value,w=weaponDefs[wid],gd=gradeDefs[gi],quality=.03+Math.random()*.055+(sameType?.045:0)+(quench==="water"?.02:0),damageMul=1+gi*.12+quality+(quench==="oil"?.025:0),item={id:`w${Date.now()}${Math.floor(Math.random()*999)}`,weapon:wid,visualId:wid,element:ability,grade:gd.id,name:`${oreTypes[ability].name} ${w.name}`,damageMul,ability,abilityName:oreTypes[ability].ability,abilityDesc:oreTypes[ability].desc,created:Date.now()};account.weapons.push(item);account.forgeCount++;saveAccountData();const resultHtml=`<b class="rarity-${gd.id}">${gd.name} ${item.name}</b> 완성<br>기본 피해 ${damageMul.toFixed(2)}배 · ${item.abilityName}: ${item.abilityDesc}`;refreshForge();ui.forgePreview.innerHTML=resultHtml}
function renderWeaponInventory(){ui.weaponInventory.innerHTML=account.weapons.length?account.weapons.slice().reverse().map(item=>{const gd=gradeDefs.find(g=>g.id===item.grade),eq=account.equipped[item.weapon]===item.id;return `<div class="weapon-item ${eq?"equipped":""}"><strong><span class="rarity-${item.grade}">${gd.name} ${item.name}</span><span>${item.damageMul.toFixed(2)}x</span></strong><p>${weaponDefs[item.weapon].name} · ${item.abilityName}: ${item.abilityDesc}</p><div class="weapon-actions"><button data-equip="${item.id}">${eq?"장착 중":"장착"}</button><button data-break="${item.id}">분해</button></div></div>`}).join(""):'<p class="desc">아직 제작한 무기가 없다.</p>';ui.weaponInventory.querySelectorAll("[data-equip]").forEach(b=>b.addEventListener("click",()=>{const item=account.weapons.find(x=>x.id===b.dataset.equip);account.equipped[item.weapon]=item.id;saveAccountData();renderWeaponInventory()}));ui.weaponInventory.querySelectorAll("[data-break]").forEach(b=>b.addEventListener("click",()=>{const i=account.weapons.findIndex(x=>x.id===b.dataset.break),item=account.weapons[i];if(i<0)return;account.gold+=35+gradeIndex(item.grade)*45;if(account.equipped[item.weapon]===item.id)delete account.equipped[item.weapon];account.weapons.splice(i,1);saveAccountData();refreshForge()}))}
